## Description

This notebook defines a function `enrich_city_maker(df, city_col=...)` that takes in the Tarisio data and adds a small set of standardized geographic columns derived **GeoNames**.

The function `enrich_city_maker(...)' add the columns:
- `country_iso1`: 2-letter country code (e.g., `US`, `FR`, `GB`)
- `admin1_name`: first-order subdivision name (state/province/region)
- `admin2_name`: second-order subdivision name (county/district/province)
- `candidate_count`: number of GeoNames matches considered for that place
- `is_ambiguous`: `True` if `candidate_count > 1`

How matching is done:
- For each unique `city_maker` value, the code looks up matching entries in the offline GeoNames dump (`allCountries.txt`) using a normalized name key (case-insensitive, diacritics removed).
- US strings like `"City, ST"` force `country=US` and `admin1=ST`.
- Each GeoNames candidate gets a score based mainly on population:
  - `score = log(1 + population)`
  - plus a small bonus if the candidate is a populated place (`feature_class = 'P'`)
- If `print_ambiguous=True`, any names with multiple candidates are printed to the console for manual review.

In [18]:
import pandas as pd

df = pd.read_csv('sales_engineered.csv')
print(df.city_maker.value_counts())

city_maker
Paris             8329
London            6163
Mirecourt         4337
Markneukirchen    2189
Cremona           1478
                  ...
Limoges              1
Capri                1
Naugatuck, CT        1
Amiens               1
Wallgau              1
Name: count, Length: 732, dtype: int64

In [19]:
import math
import re
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import pandas as pd
import unicodedata

US_STATE_ABBR = set("""
AL AK AZ AR CA CO CT DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN
MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT
WA WI WV WY DC
""".split())

US_STATE_NAME_TO_ABBR = {
    "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
    "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
    "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
    "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
    "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
    "massachusetts": "MA", "michigan": "MI", "minnesota": "MN", "mississippi": "MS",
    "missouri": "MO", "montana": "MT", "nebraska": "NE", "nevada": "NV",
    "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
    "north carolina": "NC", "north dakota": "ND", "ohio": "OH", "oklahoma": "OK",
    "oregon": "OR", "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
    "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
    "vermont": "VT", "virginia": "VA", "washington": "WA", "west virginia": "WV",
    "wisconsin": "WI", "wyoming": "WY", "district of columbia": "DC",
}

CHAR_MAP = str.maketrans({
    "ø": "o", "Ø": "O",
    "ł": "l", "Ł": "L",
    "đ": "d", "Đ": "D",
    "ð": "d", "Ð": "D",
    "þ": "th", "Þ": "Th",
    "æ": "ae", "Æ": "Ae",
    "œ": "oe", "Œ": "Oe",
})

def strip_accents(s: str) -> str:
    # Decompose + remove combining marks (accents/diacritics)
    s = unicodedata.normalize("NFKD", s)
    return "".join(ch for ch in s if not unicodedata.combining(ch))

def norm_text(s: str) -> str:
    s = "" if s is None else str(s)
    s = s.translate(CHAR_MAP)
    s = strip_accents(s)
    s = s.casefold().strip()          # better than lower(); handles ß -> ss, etc.
    s = re.sub(r"[’`]", "'", s)       # normalize apostrophes
    s = re.sub(r"[\s\-]+", " ", s)    # collapse whitespace/hyphens
    s = re.sub(r"\s+", " ", s)
    return s

def parse_place(raw: str) -> Tuple[str, Optional[str], Optional[str], Optional[str]]:
    """
    Returns: (place_core, subregion_hint, state_hint, country_hint)
    - Handles:
        "City, ST" or "City,ST" -> state_hint=ST, country_hint='US'
        "City, StateName"       -> state_hint=abbr, country_hint='US'
        "Name (Qualifier)"      -> subregion_hint=Qualifier
        Otherwise:
        if comma present -> core before comma, subregion_hint after comma
    """
    if raw is None or (isinstance(raw, float) and math.isnan(raw)):
        return ("", None, None, None)

    s = str(raw).strip()
    if not s:
        return ("", None, None, None)

    # Parentheses qualifier: "Luxeuil (Haute-Saone)"
    m_paren = re.match(r"^(.*?)\s*\((.*?)\)\s*$", s)
    if m_paren:
        core = m_paren.group(1).strip()
        qual = m_paren.group(2).strip()
        return (core, qual or None, None, None)

    # Comma suffix: "New York, NY" or "Worthing, Sussex"
    if "," in s:
        left, right = s.rsplit(",", 1)
        left = left.strip()
        right_stripped = right.strip()

        # "City, ST"
        m_abbr = re.match(r"^([A-Za-z]{2})$", right_stripped)
        if m_abbr:
            st = m_abbr.group(1).upper()
            if st in US_STATE_ABBR:
                return (left, None, st, "US")

        # "City, StateName"
        right_norm = norm_text(right_stripped)
        if right_norm in US_STATE_NAME_TO_ABBR:
            st = US_STATE_NAME_TO_ABBR[right_norm]
            return (left, None, st, "US")

        # Otherwise treat comma part as a generic subregion hint
        return (left, right_stripped or None, None, None)

    return (s, None, None, None)


# GeoNames loading 
@dataclass(frozen=True)
class Candidate:
    geonameid: str
    name: str
    country: str
    admin1: str
    admin2: str
    feature_class: str
    feature_code: str
    population: int

def load_admin1(admin1_path: str) -> Dict[str, str]:
    # admin1CodesASCII.txt: "CC.ADM1\tName\t..."
    m = {}
    with open(admin1_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            key = parts[0].strip()
            name = parts[1].strip()
            if key:
                m[key] = name
    return m

def load_admin2(admin2_path: str) -> Dict[str, str]:
    # admin2Codes.txt: "CC.ADM1.ADM2\tName\t..."
    m = {}
    with open(admin2_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            key = parts[0].strip()
            name = parts[1].strip()
            if key:
                m[key] = name
    return m


def build_candidates_index(
    geonames_path: str,
    target_keys: set,
    include_admin_features: bool = True,
) -> Dict[str, List[Candidate]]:
    """
    Streams allCountries.txt once, collecting candidates only for keys in target_keys.
    Pass 1: match on (normalized) asciiname and name.
    Pass 2: (optional) match on alternatenames only for keys still unmatched.

    Keeps:
      - feature_class 'P' (populated places)
      - plus (optional) feature_class 'A' with admin codes (ADM1/ADM2/...)
    """
    allowed_A_codes = {"ADM1", "ADM2", "ADM3", "ADM4", "ADMD", "ADM5"}

    cand_by_key: Dict[str, List[Candidate]] = {k: [] for k in target_keys}

    def maybe_add(key: str, parts: List[str]) -> None:
        # columns per GeoNames readme:
        # 0 geonameid, 1 name, 2 asciiname, 3 alternatenames, 6 fclass, 7 fcode,
        # 8 country, 10 admin1, 11 admin2, 14 population
        fclass = parts[6]
        fcode = parts[7]
        if fclass == "P":
            pass
        elif include_admin_features and fclass == "A" and fcode in allowed_A_codes:
            pass
        else:
            return

        try:
            pop = int(parts[14]) if parts[14] else 0
        except ValueError:
            pop = 0

        cand_by_key[key].append(
            Candidate(
                geonameid=parts[0],
                name=parts[1],
                country=parts[8],
                admin1=parts[10],
                admin2=parts[11],
                feature_class=fclass,
                feature_code=fcode,
                population=pop,
            )
        )

    # pass 1: asciiname/name
    with open(geonames_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 15:
                continue

            key_ascii = norm_text(parts[2])
            if key_ascii in target_keys:
                maybe_add(key_ascii, parts)

            key_name = norm_text(parts[1])
            if key_name in target_keys and key_name != key_ascii:
                maybe_add(key_name, parts)

    # find unmatched keys
    unmatched = {k for k, v in cand_by_key.items() if len(v) == 0}
    if not unmatched:
        return cand_by_key

    #  pass 2: alternatenames for unmatched only
    with open(geonames_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 15:
                continue

            alts = parts[3]
            if not alts:
                continue

            # quick skip: if we already matched all, stop
            if not unmatched:
                break

            # Normalize alternatenames and test membership in unmatched.
            # This is the expensive part; we only do it for the remaining unmatched keys.
            for alt in alts.split(","):
                k = norm_text(alt)
                if k in unmatched:
                    maybe_add(k, parts)

    return cand_by_key


# Main function to enrich city_maker with GeoNames data

def enrich_city_maker(
    df: pd.DataFrame,
    city_col: str = "city_maker",
    geonames_path: str = "allCountries.txt",
    admin1_path: str = "admin1CodesASCII.txt",
    admin2_path: str = "admin2Codes.txt",
    print_ambiguous: bool = True,
    top_k_print: int = 5,
) -> pd.DataFrame:
    """
    Adds columns:
      - country_iso1 (GeoNames country_code, e.g., 'US', 'FR', 'GB')
      - admin1_name
      - admin2_name
      - candidate_count
      - is_ambiguous

    Prints ambiguous place strings to console with top candidate suggestions.
    Handles missing/blank city_maker gracefully.
    """
    out = df.copy()

    if city_col not in out.columns:
        raise ValueError(f"Column '{city_col}' not found in dataframe.")

    # Parse unique places (skip NaN/empty)
    uniques = pd.Series(out[city_col].dropna().unique())
    parsed = []
    for raw in uniques.tolist():
        core, sub_hint, st_hint, c_hint = parse_place(raw)
        key = norm_text(core)
        if key:
            parsed.append((raw, core, sub_hint, st_hint, c_hint, key))

    if not parsed:
        # Add empty columns and return
        out["country_iso1"] = pd.NA
        out["admin1_name"] = pd.NA
        out["admin2_name"] = pd.NA
        out["candidate_count"] = pd.NA
        out["is_ambiguous"] = False
        return out

    places = pd.DataFrame(parsed, columns=["place_raw", "place_core", "subregion_hint", "state_hint", "country_hint", "place_key"])

    # Load decoding maps
    admin1_map = load_admin1(admin1_path)
    admin2_map = load_admin2(admin2_path)

    # Build candidate index for all needed keys
    target_keys = set(places["place_key"].unique())
    cand_by_key = build_candidates_index(geonames_path, target_keys, include_admin_features=True)

    # For each unique raw place, pick best candidate using hints 
    resolved_rows = []
    ambiguous_reports = []

    def score_candidate(c: Candidate) -> float:
        s = math.log1p(max(c.population, 0))
        if c.feature_class == "P":
            s += 2.0
        return s

    for _, r in places.iterrows():
        raw = r["place_raw"]
        key = r["place_key"]
        st_hint = r["state_hint"]
        c_hint = r["country_hint"]

        candidates = cand_by_key.get(key, [])
        # Apply country/state hints when present
        filtered = candidates

        if c_hint:
            filtered = [c for c in filtered if c.country == c_hint]

        if st_hint:
            # GeoNames admin1_code for US states aligns with keys in admin1CodesASCII like "US.NY"
            filtered2 = [c for c in filtered if c.country == "US" and c.admin1 == st_hint]
            if filtered2:
                filtered = filtered2

        # If filtering removed everything, fall back to unfiltered 
        if not filtered:
            filtered = candidates

        scored = [(score_candidate(c), c) for c in filtered]
        scored.sort(key=lambda t: t[0], reverse=True)

        cand_count = len(filtered)
        is_amb = cand_count > 1

        if scored:
            best_c = scored[0][1]
            country_iso1 = best_c.country or pd.NA

            a1_key = f"{best_c.country}.{best_c.admin1}" if best_c.country and best_c.admin1 else None
            admin1_name = admin1_map.get(a1_key, pd.NA) if a1_key else pd.NA

            a2_key = f"{best_c.country}.{best_c.admin1}.{best_c.admin2}" if best_c.country and best_c.admin1 and best_c.admin2 else None
            admin2_name = admin2_map.get(a2_key, pd.NA) if a2_key else pd.NA
        else:
            # no match at all
            country_iso1 = pd.NA
            admin1_name = pd.NA
            admin2_name = pd.NA
            cand_count = 0
            is_amb = False

        resolved_rows.append({
            "place_raw": raw,
            "country_iso1": country_iso1,
            "admin1_name": admin1_name,
            "admin2_name": admin2_name,
            "candidate_count": cand_count,
            "is_ambiguous": bool(is_amb),
        })

        if print_ambiguous and is_amb and scored:
            # Print a compact report with top options
            top = scored[:top_k_print]
            opts = []
            for s_val, c in top:
                a1 = admin1_map.get(f"{c.country}.{c.admin1}", "")
                a2 = admin2_map.get(f"{c.country}.{c.admin1}.{c.admin2}", "")
                opts.append((s_val, c.name, c.country, a1, a2, c.population))
            ambiguous_reports.append((raw, cand_count, opts))

    mapping = pd.DataFrame(resolved_rows).drop_duplicates("place_raw")
    out = out.merge(mapping, left_on=city_col, right_on="place_raw", how="left").drop(columns=["place_raw"])

    # Ensure rows with missing city_maker remain clean (merge will keep NaNs)
    out["is_ambiguous"] = out["is_ambiguous"].fillna(False).astype(bool)

    # Console printing
    if print_ambiguous and ambiguous_reports:
        print("\n--- Ambiguous place names (review recommended) ---")
        for raw, n, opts in ambiguous_reports:
            print(f"\nAMBIGUOUS: '{raw}' (candidates={n})")
            for s_val, name, cc, a1, a2, pop in opts:
                a1_txt = f" | admin1={a1}" if a1 else ""
                a2_txt = f" | admin2={a2}" if a2 else ""
                print(f"  score={s_val:0.3f} | {name} | {cc}{a1_txt}{a2_txt} | pop={pop}")

    return out

No need to run next cell because I improve the function after this, this was just me checking the initial function outputs

In [ ]:

df2 = enrich_city_maker(
    df,
    city_col="city_maker",
    geonames_path="Data/Geo_Data/allCountries.txt",
    admin1_path="Data/Geo_Data/admin1CodesASCII.txt",
    admin2_path="Data/Geo_Data/admin2Codes.txt",
    print_ambiguous=True,
)
# df2.to_csv("cozio_sales_grouped_by_region.csv", index=False)

--- Ambiguous place names (review recommended) ---

AMBIGUOUS: 'Wallgau' (candidates=2)
  score=9.277 | Wallgau | DE | admin1=Bavaria | admin2=Upper Bavaria | pop=1446
  score=7.324 | Wallgau | DE | admin1=Bavaria | admin2=Upper Bavaria | pop=1516

AMBIGUOUS: 'Paris' (candidates=59)
  score=16.576 | Paris | FR | admin1=Île-de-France | admin2=Paris | pop=2138551
  score=15.293 | Paris | FR | admin1=Île-de-France | admin2=Paris | pop=4380654
  score=14.600 | Paris | FR | admin1=Île-de-France | admin2=Paris | pop=2190327
  score=14.533 | Paris | FR | admin1=Île-de-France | admin2=Paris | pop=2048472
  score=12.118 | Paris | US | admin1=Texas | admin2=Lamar County | pop=24782

AMBIGUOUS: 'Mirecourt' (candidates=2)
  score=10.854 | Mirecourt | FR | admin1=Grand Est | admin2=Vosges | pop=6998
  score=8.573 | Mirecourt | FR | admin1=Grand Est | admin2=Vosges | pop=5285

AMBIGUOUS: 'London' (candidates=34)
  score=18.009 | London | GB | admin1=England | admin2=Greater London | pop=8961989
  score=14.954 | London | CA | admin1=Ontario | admin2=Middlesex County | pop=422324
  score=11.216 | London | US | admin1=Ohio | admin2=Madison County | pop=10060
  score=11.003 | London | US | admin1=Kentucky | admin2=Laurel County | pop=8126
  score=9.534 | London | US | admin1=California | admin2=Tulare County | pop=1869

AMBIGUOUS: 'Copenhagen' (candidates=6)
  score=15.958 | Copenhagen | DK | admin1=Capital Region | admin2=København | pop=1153615
  score=8.686 | Copenhagen | US | admin1=New York | admin2=Lewis County | pop=800
  score=2.000 | Copenhagen | CA | admin1=Ontario | admin2=Elgin County | pop=0
  score=2.000 | Copenhagen | GB | admin1=Wales | admin2=Denbighshire | pop=0
  score=2.000 | Copenhagen | US | admin1=Louisiana | admin2=Caldwell Parish | pop=0

AMBIGUOUS: 'Manchester' (candidates=44)
  score=15.252 | Manchester | GB | admin1=England | admin2=Manchester | pop=568996
  score=13.610 | Manchester | US | admin1=New Hampshire | admin2=Hillsborough County | pop=110229
  score=13.202 | Manchester | GB | admin1=England | admin2=Manchester | pop=541263
  score=12.328 | Manchester | US | admin1=Connecticut | admin2=Capitol Planning Region | pop=30577
  score=12.164 | Manchester | JM | admin1=Manchester | pop=191796

AMBIGUOUS: 'Markneukirchen' (candidates=2)
  score=10.867 | Markneukirchen | DE | admin1=Saxony | pop=7095
  score=8.862 | Markneukirchen | DE | admin1=Saxony | pop=7061

AMBIGUOUS: 'Brussels' (candidates=4)
  score=15.834 | Brussels | BE | admin1=Brussels Capital | admin2=Bruxelles-Capitale | pop=1019022
  score=9.055 | Brussels | CA | admin1=Ontario | admin2=Huron County | pop=1158
  score=9.013 | Brussels | US | admin1=Wisconsin | admin2=Door County | pop=1110
  score=6.920 | Brussels | US | admin1=Illinois | admin2=Calhoun County | pop=136

AMBIGUOUS: 'Milan' (candidates=46)
  score=16.131 | Milan | IT | admin1=Lombardy | admin2=Città metropolitana di Milano | pop=1371498
  score=10.964 | Milan | US | admin1=Tennessee | admin2=Gibson County | pop=7813
  score=10.924 | Milán | CO | admin1=Caquetá | admin2=Milán | pop=7507
  score=10.697 | Milan | US | admin1=Michigan | admin2=Monroe County | pop=5983
  score=10.536 | Milan | US | admin1=Illinois | admin2=Rock Island County | pop=5096

AMBIGUOUS: 'Turin' (candidates=16)
  score=15.650 | Turin | IT | admin1=Piedmont | admin2=Torino | pop=847287
  score=11.378 | Turín | SV | admin1=Ahuachapán | pop=11829
  score=7.841 | Turin | US | admin1=Georgia | admin2=Coweta County | pop=343
  score=7.442 | Turin | US | admin1=New York | admin2=Lewis County | pop=230
  score=6.205 | Turin | US | admin1=Iowa | admin2=Monona County | pop=66

AMBIGUOUS: 'Vidigulfo' (candidates=2)
  score=10.463 | Vidigulfo | IT | admin1=Lombardy | admin2=Provincia di Pavia | pop=4735
  score=8.781 | Vidigulfo | IT | admin1=Lombardy | admin2=Provincia di Pavia | pop=6508

AMBIGUOUS: 'Pavia' (candidates=10)
  score=13.093 | Pavia | IT | admin1=Lombardy | admin2=Provincia di Pavia | pop=65734
  score=11.220 | Pavia | PH | admin1=Western Visayas | admin2=Province of Iloilo | pop=74594
  score=11.199 | Pavia | IT | admin1=Lombardy | admin2=Provincia di Pavia | pop=73086
  score=10.688 | Pavia | PH | admin1=Western Visayas | admin2=Province of Iloilo | pop=5928
  score=6.574 | Pavia | PT | admin1=Évora | admin2=Mora | pop=715

AMBIGUOUS: 'Bologna' (candidates=6)
  score=14.886 | Bologna | IT | admin1=Emilia-Romagna | admin2=Bologna | pop=394843
  score=13.830 | Bologna | IT | admin1=Emilia-Romagna | admin2=Bologna | pop=1014619
  score=12.876 | Bologna | IT | admin1=Emilia-Romagna | admin2=Bologna | pop=390636
  score=5.332 | Bologna | IT | admin1=Piedmont | admin2=Provincia di Asti | pop=27
  score=4.944 | Bologna | IT | admin1=Emilia-Romagna | admin2=Provincia di Ferrara | pop=18

AMBIGUOUS: 'Bolzano' (candidates=3)
  score=13.585 | Bolzano | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | pop=107436
  score=13.183 | Bolzano | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | pop=531178
  score=2.000 | Bolzano | IT | admin1=Friuli Venezia Giulia | admin2=Udine | pop=0

AMBIGUOUS: 'Graz' (candidates=2)
  score=14.622 | Graz | AT | admin1=Styria | admin2=Graz Stadt | pop=303270
  score=12.556 | Graz | AT | admin1=Styria | admin2=Graz Stadt | pop=283869

AMBIGUOUS: 'Gorham' (candidates=6)
  score=10.837 | Gorham | US | admin1=Maine | admin2=Cumberland County | pop=6882
  score=9.378 | Gorham | US | admin1=New Hampshire | admin2=Coos County | pop=1600
  score=8.426 | Gorham | US | admin1=New York | admin2=Ontario County | pop=617
  score=7.832 | Gorham | US | admin1=Kansas | admin2=Russell County | pop=340
  score=7.455 | Gorham | US | admin1=Illinois | admin2=Jackson County | pop=233

AMBIGUOUS: 'Nantes' (candidates=10)
  score=14.692 | Nantes | FR | admin1=Pays de la Loire | admin2=Loire-Atlantique | pop=325070
  score=12.634 | Nantes | FR | admin1=Pays de la Loire | admin2=Loire-Atlantique | pop=306694
  score=9.886 | Nantes | BR | admin1=São Paulo | admin2=Nantes | pop=2660
  score=8.065 | Nantes | BR | admin1=São Paulo | admin2=Nantes | pop=3179
  score=2.000 | Nantes | CA | admin1=Quebec | admin2=Estrie | pop=0

AMBIGUOUS: 'Birmingham' (candidates=20)
  score=15.962 | Birmingham | GB | admin1=England | admin2=City and Borough of Birmingham | pop=1157603
  score=14.188 | Birmingham | US | admin1=Alabama | admin2=Jefferson County | pop=196357
  score=11.945 | Birmingham | US | admin1=Michigan | admin2=Oakland County | pop=20857
  score=8.073 | Birmingham | US | admin1=Iowa | admin2=Van Buren County | pop=433
  score=7.268 | Birmingham | US | admin1=Missouri | admin2=Clay County | pop=193

AMBIGUOUS: 'Munich' (candidates=4)
  score=16.047 | Munich | DE | admin1=Bavaria | admin2=Upper Bavaria | pop=1260391
  score=7.313 | Munich | US | admin1=North Dakota | admin2=Cavalier County | pop=202
  score=2.000 | Munich | GD | admin1=Saint Andrew Parish | pop=0
  score=2.000 | Munich | PE | admin1=Loreto | admin2=Provincia de Maynas | pop=0

AMBIGUOUS: 'Barnstaple' (candidates=4)
  score=12.361 | Barnstaple | GB | admin1=England | admin2=Devon | pop=31616
  score=2.000 | Barnstaple | JM | admin1=Trelawny Parish | admin2=Jackson Town | pop=0
  score=2.000 | Barnstaple | JM | admin1=Saint Ann Parish | admin2=Madras | pop=0
  score=0.000 | Barnstaple | GB | admin1=England | admin2=Devon | pop=0

AMBIGUOUS: 'Madrid' (candidates=29)
  score=16.996 | Madrid | ES | admin1=Madrid | admin2=Provincia de Madrid | pop=3255944
  score=14.989 | Madrid | ES | admin1=Madrid | admin2=Provincia de Madrid | pop=3233527
  score=13.813 | Madrid | CO | admin1=Cundinamarca | admin2=Madrid | pop=135000
  score=11.351 | Madrid | CO | admin1=Cundinamarca | admin2=Madrid | pop=85090
  score=10.240 | Madrid | MX | admin1=Colima | admin2=Tecomán | pop=3790

AMBIGUOUS: 'Naples' (candidates=14)
  score=15.720 | Naples | IT | admin1=Campania | admin2=Napoli | pop=909048
  score=11.976 | Naples | US | admin1=Florida | admin2=Collier County | pop=21512
  score=9.702 | Naples | US | admin1=Utah | admin2=Uintah County | pop=2212
  score=9.200 | Naples | US | admin1=Texas | admin2=Morris County | pop=1339
  score=8.928 | Naples | US | admin1=New York | admin2=Ontario County | pop=1019

AMBIGUOUS: 'Gerona' (candidates=5)
  score=12.619 | Gerona | PH | admin1=Central Luzon | admin2=Province of Tarlac | pop=40914
  score=11.492 | Gerona | PH | admin1=Central Luzon | admin2=Province of Tarlac | pop=97937
  score=2.000 | Gerona | CO | admin1=Antioquia | admin2=Medellín | pop=0
  score=2.000 | Gerona | UY | admin1=Maldonado | admin2=Pan De Azucar | pop=0
  score=0.000 | Gerona | CO | admin1=Antioquia | admin2=Medellín | pop=0

AMBIGUOUS: 'Augsburg' (candidates=7)
  score=14.465 | Augsburg | DE | admin1=Bavaria | admin2=Swabia | pop=259196
  score=12.615 | Augsburg | DE | admin1=Bavaria | admin2=Swabia | pop=301105
  score=2.000 | Augsburg | CA | admin1=Ontario | admin2=Renfrew County | pop=0
  score=2.000 | Augsburg | DE | admin1=Schleswig-Holstein | pop=0
  score=2.000 | Augsburg | US | admin1=Arkansas | admin2=Pope County | pop=0

AMBIGUOUS: 'Cremona' (candidates=5)
  score=13.174 | Cremona | IT | admin1=Lombardy | admin2=Provincia di Cremona | pop=71223
  score=11.194 | Cremona | IT | admin1=Lombardy | admin2=Provincia di Cremona | pop=72680
  score=8.082 | Cremona | CA | admin1=Alberta | admin2=Mountain View County | pop=437
  score=2.000 | Cremona | US | admin1=Maryland | admin2=Saint Mary's County | pop=0
  score=0.000 | Cremona | CA | admin1=Alberta | admin2=Cremona | pop=0

AMBIGUOUS: 'Edinburgh' (candidates=10)
  score=15.152 | Edinburgh | GB | admin1=Scotland | admin2=City of Edinburgh | pop=514990
  score=10.422 | Edinburgh | US | admin1=Indiana | admin2=Johnson County | pop=4546
  score=7.707 | Edinburgh | AU | admin1=South Australia | admin2=Salisbury | pop=300
  score=2.000 | Edinburgh | GY | admin1=Essequibo Islands-West Demerara | pop=0
  score=2.000 | Edinburgh | JM | admin1=Manchester | admin2=Snowdon | pop=0

AMBIGUOUS: 'Lugano' (candidates=4)
  score=13.054 | Lugano | CH | admin1=Ticino | admin2=Lugano District | pop=63185
  score=11.045 | Lugano | CH | admin1=Ticino | admin2=Lugano District | pop=62615
  score=2.000 | Lugano | BR | admin1=Rio de Janeiro | admin2=Itatiaia | pop=0
  score=2.000 | Lugano | UG | admin1=Eastern Region | admin2=Bugiri District | pop=0

AMBIGUOUS: 'Bangor' (candidates=24)
  score=13.019 | Bangor | GB | admin1=Northern Ireland | admin2=Ards and North Down | pop=61011
  score=12.386 | Bangor | US | admin1=Maine | admin2=Penobscot County | pop=32391
  score=11.816 | Bangor | GB | admin1=Wales | admin2=Gwynedd | pop=18322
  score=10.607 | Bangor | AU | admin1=New South Wales | admin2=Sutherland | pop=5471
  score=10.557 | Bangor | US | admin1=Pennsylvania | admin2=Northampton County | pop=5203

AMBIGUOUS: 'Vienna' (candidates=19)
  score=16.341 | Vienna | AT | admin1=Vienna | admin2=Wien Stadt | pop=1691468
  score=11.713 | Vienna | US | admin1=Virginia | admin2=Fairfax County | pop=16522
  score=11.266 | Vienna | US | admin1=West Virginia | admin2=Wood County | pop=10573
  score=10.237 | Vienna | US | admin1=Georgia | admin2=Dooly County | pop=3777
  score=9.407 | Vienna | US | admin1=Illinois | admin2=Johnson County | pop=1647

AMBIGUOUS: 'Grand Rapids, MI' (candidates=2)
  score=14.181 | Grand Rapids | US | admin1=Michigan | admin2=Kent County | pop=195097
  score=2.000 | Grand Rapids | US | admin1=Michigan | admin2=Ontonagon County | pop=0

AMBIGUOUS: 'Salerno' (candidates=4)
  score=13.742 | Salerno | IT | admin1=Campania | admin2=Provincia di Salerno | pop=125797
  score=11.801 | Salerno | IT | admin1=Campania | admin2=Provincia di Salerno | pop=133364
  score=5.970 | Salerno | IT | admin1=Lombardy | admin2=Provincia di Pavia | pop=52
  score=2.000 | Salerno | PK | admin1=Punjab | admin2=Okāra District | pop=0

AMBIGUOUS: 'Mantua' (candidates=11)
  score=11.287 | Mantua | CU | admin1=Pinar del Río | admin2=Municipio de Mantua | pop=10797
  score=10.873 | Mantua | US | admin1=Virginia | admin2=Fairfax County | pop=7135
  score=10.829 | Mantua | US | admin1=Pennsylvania | admin2=Philadelphia County | pop=6829
  score=8.930 | Mantua | US | admin1=Ohio | admin2=Portage County | pop=1021
  score=8.917 | Mantua | US | admin1=Ohio | admin2=Guernsey County | pop=1008

AMBIGUOUS: 'Colle' (candidates=41)
  score=8.114 | Colle | IT | admin1=Umbria | admin2=Provincia di Terni | pop=451
  score=7.869 | Colle | IT | admin1=Veneto | admin2=Provincia di Vicenza | pop=353
  score=7.412 | Colle | IT | admin1=Friuli Venezia Giulia | admin2=Pordenone | pop=223
  score=7.165 | Colle | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | pop=174
  score=7.004 | Colle | IT | admin1=The Marches | admin2=Provincia di Ascoli Piceno | pop=148

AMBIGUOUS: 'Florence' (candidates=47)
  score=14.814 | Florence | IT | admin1=Tuscany | admin2=Province of Florence | pop=367150
  score=12.597 | Florence | US | admin1=Alabama | admin2=Lauderdale County | pop=40026
  score=12.551 | Florence | US | admin1=South Carolina | admin2=Florence County | pop=38228
  score=12.381 | Florence | US | admin1=Kentucky | admin2=Boone County | pop=32227
  score=12.345 | Florence | US | admin1=Arizona | admin2=Pinal County | pop=31110

AMBIGUOUS: 'Como' (candidates=27)
  score=13.348 | Como | IT | admin1=Lombardy | admin2=Provincia di Como | pop=84808
  score=11.602 | Como | AU | admin1=Western Australia | admin2=South Perth | pop=14786
  score=11.321 | Como | IT | admin1=Lombardy | admin2=Provincia di Como | pop=82522
  score=10.266 | Como | AU | admin1=New South Wales | admin2=Sutherland | pop=3890
  score=9.875 | Como | US | admin1=Wisconsin | admin2=Walworth County | pop=2631

AMBIGUOUS: 'Cheshire' (candidates=6)
  score=12.290 | Cheshire | US | admin1=Connecticut | admin2=Naugatuck Valley Planning Region | pop=29443
  score=8.244 | Cheshire | US | admin1=Massachusetts | admin2=Berkshire County | pop=514
  score=6.883 | Cheshire | US | admin1=Ohio | admin2=Gallia County | pop=131
  score=6.078 | Cheshire | US | admin1=Ohio | admin2=Delaware County | pop=58
  score=2.000 | Cheshire | US | admin1=New York | admin2=Ontario County | pop=0

AMBIGUOUS: 'Lichfield' (candidates=4)
  score=12.401 | Lichfield | GB | admin1=England | admin2=Staffordshire | pop=32877
  score=2.000 | Lichfield | GY | admin1=Mahaica-Berbice | pop=0
  score=2.000 | Lichfield | NZ | admin1=Waikato Region | admin2=South Waikato District | pop=0
  score=0.000 | Lichfield | GB | admin1=England | admin2=Staffordshire | pop=0

AMBIGUOUS: 'Tottenham' (candidates=4)
  score=13.775 | Tottenham | GB | admin1=England | admin2=Greater London | pop=130000
  score=10.546 | Tottenham | CA | admin1=Ontario | admin2=Simcoe County | pop=5143
  score=8.089 | Tottenham | AU | admin1=New South Wales | admin2=Lachlan | pop=440
  score=2.000 | Tottenham | AU | admin1=Victoria | admin2=Maribyrnong | pop=0

AMBIGUOUS: 'Troyes' (candidates=3)
  score=13.015 | Troyes | FR | admin1=Grand Est | admin2=Aube | pop=60785
  score=11.013 | Troyes | FR | admin1=Grand Est | admin2=Aube | pop=60640
  score=2.000 | Troyes | FR | admin1=Nouvelle-Aquitaine | admin2=Landes | pop=0

AMBIGUOUS: 'Le Havre' (candidates=3)
  score=14.133 | Le Havre | FR | admin1=Normandy | admin2=Seine-Maritime | pop=185972
  score=12.046 | Le Havre | FR | admin1=Normandy | admin2=Seine-Maritime | pop=170352
  score=2.000 | Le Havre | FR | admin1=Normandy | admin2=Manche | pop=0

AMBIGUOUS: 'Rome' (candidates=33)
  score=16.657 | Rome | IT | admin1=Lazio | admin2=Città metropolitana di Roma Capitale | pop=2318895
  score=12.500 | Rome | US | admin1=Georgia | admin2=Floyd County | pop=36323
  score=12.391 | Rome | US | admin1=New York | admin2=Oneida County | pop=32573
  score=9.900 | Rome | US | admin1=Wisconsin | admin2=Adams County | pop=2697
  score=9.461 | Rome | US | admin1=Illinois | admin2=Peoria County | pop=1738

AMBIGUOUS: 'Palermo' (candidates=70)
  score=15.382 | Palermo | IT | admin1=Sicily | admin2=Palermo | pop=648260
  score=14.041 | Palermo | IT | admin1=Sicily | admin2=Palermo | pop=1252588
  score=13.405 | Palermo | IT | admin1=Sicily | admin2=Palermo | pop=663401
  score=11.200 | Palermo | CO | admin1=Huila Department | admin2=Palermo | pop=9896
  score=10.591 | Palermo | US | admin1=California | admin2=Butte County | pop=5382

AMBIGUOUS: 'Caltanisetta' (candidates=2)
  score=13.048 | Caltanissetta | IT | admin1=Sicily | admin2=Provincia di Caltanissetta | pop=62797
  score=12.478 | Provincia di Caltanissetta | IT | admin1=Sicily | admin2=Provincia di Caltanissetta | pop=262458

AMBIGUOUS: 'Berlin' (candidates=146)
  score=17.047 | Berlin | DE | admin1=State of Berlin | pop=3426354
  score=15.120 | Berlin | DE | admin1=State of Berlin | pop=3685265
  score=11.334 | Berlín | SV | admin1=Usulután | pop=11313
  score=11.145 | Berlin | US | admin1=New Hampshire | admin2=Coos County | pop=9367
  score=10.935 | Berlin | US | admin1=New Jersey | admin2=Camden County | pop=7590

AMBIGUOUS: 'Pisa' (candidates=17)
  score=13.608 | Pisa | IT | admin1=Tuscany | admin2=Province of Pisa | pop=109960
  score=11.395 | Pisa | IT | admin1=Tuscany | admin2=Province of Pisa | pop=88880
  score=3.386 | Pisa | PE | admin1=Arequipa | admin2=Provincia de Caylloma | pop=3
  score=2.000 | Pisa | CN | admin1=Yunnan | admin2=Wenshan Zhuangzu Miaozu Zizhizhou | pop=0
  score=2.000 | Pisa | CO | admin1=Sucre Department | admin2=Majagual | pop=0

AMBIGUOUS: 'Padua' (candidates=23)
  score=11.868 | Padua | CO | admin1=Tolima Department | admin2=Herveo | pop=19311
  score=10.907 | Padua | IN | admin1=Odisha | admin2=Koraput | pop=54561
  score=2.000 | Padua | AU | admin1=New South Wales | admin2=Cowra | pop=0
  score=2.000 | Padua | BD | admin1=Chittagong | admin2=Cumilla | pop=0
  score=2.000 | Padua | BD | admin1=Chittagong | admin2=Chandpur | pop=0

AMBIGUOUS: 'Leeds' (candidates=21)
  score=15.192 | Leeds | GB | admin1=England | admin2=City and Borough of Leeds | pop=536280
  score=11.387 | Leeds | US | admin1=Alabama | admin2=Jefferson County | pop=11936
  score=9.641 | Leeds | US | admin1=Maine | admin2=Androscoggin County | pop=2080
  score=8.737 | Leeds | US | admin1=Utah | admin2=Washington County | pop=842
  score=8.195 | Leeds | JM | admin1=St. Elizabeth | admin2=Leeds | pop=3621

AMBIGUOUS: 'Brighton' (candidates=60)
  score=14.532 | Brighton | GB | admin1=England | admin2=Brighton and Hove | pop=277103
  score=12.736 | Brighton | US | admin1=Massachusetts | admin2=Suffolk County | pop=45977
  score=12.534 | Brighton | US | admin1=Colorado | admin2=Adams County | pop=37585
  score=12.508 | Brighton | US | admin1=New York | admin2=Monroe County | pop=36609
  score=12.054 | Brighton | AU | admin1=Victoria | admin2=Bayside (Vic.) | pop=23252

AMBIGUOUS: 'Oxford' (candidates=51)
  score=13.996 | Oxford | GB | admin1=England | admin2=Oxfordshire | pop=162100
  score=12.013 | Oxford | US | admin1=Mississippi | admin2=Lafayette County | pop=22314
  score=12.004 | Oxford | US | admin1=Ohio | admin2=Butler County | pop=22104
  score=11.964 | Oxford | US | admin1=Alabama | admin2=Calhoun County | pop=21249
  score=11.337 | Oxford | US | admin1=Connecticut | admin2=Naugatuck Valley Planning Region | pop=11345

AMBIGUOUS: 'Budapest' (candidates=4)
  score=16.370 | Budapest | HU | admin1=Budapest | pop=1741041
  score=14.376 | Budapest | HU | admin1=Budapest | pop=1752286
  score=2.000 | Budapest | US | admin1=Georgia | admin2=Haralson County | pop=0
  score=2.000 | Budapest | US | admin1=Missouri | admin2=Ripley County | pop=0

AMBIGUOUS: 'Perugia' (candidates=2)
  score=13.696 | Perugia | IT | admin1=Umbria | admin2=Provincia di Perugia | pop=120137
  score=12.019 | Perugia | IT | admin1=Umbria | admin2=Provincia di Perugia | pop=165956

AMBIGUOUS: 'Ancona' (candidates=5)
  score=13.408 | Ancona | IT | admin1=The Marches | admin2=Provincia di Ancona | pop=89994
  score=11.523 | Ancona | IT | admin1=The Marches | admin2=Provincia di Ancona | pop=101043

# Manually Checking Candidates #
Most of the town names have multiple matches. Most of them are safe to assume they are the top scored candidate (e.g. when the other candidates all have population 0 or when some towns are listed twice in the geonames data). The more ambiguous ones I have to crosscheck with the maker data manually to see what country they were based in. So I rewrite the function so that:
- The candidate with the highest score is selected.
- For some names, hard-coded overrides force the intended country and/or lookup name; if no match exists under the forced country, the result is left blank.

In [20]:
import math
import re
import unicodedata
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple, Union

import pandas as pd


# ----------------------------- Normalization -----------------------------

CHAR_MAP = str.maketrans({
    "ø": "o", "Ø": "O",
    "ł": "l", "Ł": "L",
    "đ": "d", "Đ": "D",
    "ð": "d", "Ð": "D",
    "þ": "th", "Þ": "Th",
    "æ": "ae", "Æ": "Ae",
    "œ": "oe", "Œ": "Oe",
})

def strip_accents(s: str) -> str:
    s = unicodedata.normalize("NFKD", s)
    return "".join(ch for ch in s if not unicodedata.combining(ch))

def norm_text(s: str) -> str:
    s = "" if s is None else str(s)
    s = s.translate(CHAR_MAP)
    s = strip_accents(s)
    s = s.casefold().strip()
    s = re.sub(r"[’`]", "'", s)
    s = re.sub(r"[\s\-]+", " ", s)
    s = re.sub(r"\s+", " ", s)
    return s


# ----------------------------- Parsing helpers -----------------------------

US_STATE_ABBR = set("""
AL AK AZ AR CA CO CT DE FL GA HI IA ID IL IN KS KY LA MA MD ME MI MN
MO MS MT NC ND NE NH NJ NM NV NY OH OK OR PA RI SC SD TN TX UT VA VT
WA WI WV WY DC
""".split())

US_STATE_NAME_TO_ABBR = {
    "alabama": "AL", "alaska": "AK", "arizona": "AZ", "arkansas": "AR",
    "california": "CA", "colorado": "CO", "connecticut": "CT", "delaware": "DE",
    "florida": "FL", "georgia": "GA", "hawaii": "HI", "idaho": "ID",
    "illinois": "IL", "indiana": "IN", "iowa": "IA", "kansas": "KS",
    "kentucky": "KY", "louisiana": "LA", "maine": "ME", "maryland": "MD",
    "massachusetts": "MA", "michigan": "MI", "minnesota": "MN", "mississippi": "MS",
    "missouri": "MO", "montana": "MT", "nebraska": "NE", "nevada": "NV",
    "new hampshire": "NH", "new jersey": "NJ", "new mexico": "NM", "new york": "NY",
    "north carolina": "NC", "north dakota": "ND", "ohio": "OH", "oklahoma": "OK",
    "oregon": "OR", "pennsylvania": "PA", "rhode island": "RI", "south carolina": "SC",
    "south dakota": "SD", "tennessee": "TN", "texas": "TX", "utah": "UT",
    "vermont": "VT", "virginia": "VA", "washington": "WA", "west virginia": "WV",
    "wisconsin": "WI", "wyoming": "WY", "district of columbia": "DC",
}

def parse_place(raw: str) -> Tuple[str, Optional[str], Optional[str], Optional[str]]:
    """
    Returns: (place_core, subregion_hint, state_hint, country_hint)

    - "City, ST" -> state_hint=ST, country_hint='US'
    - "City, StateName" -> state_hint=abbr, country_hint='US'
    - "Name (Qualifier)" -> place_core=Name, subregion_hint=Qualifier
    - Non-US comma suffix like "Worthing, Sussex" -> subregion_hint="Sussex"
    """
    if raw is None or (isinstance(raw, float) and math.isnan(raw)):
        return ("", None, None, None)

    s = str(raw).strip()
    if not s:
        return ("", None, None, None)

    m_paren = re.match(r"^(.*?)\s*\((.*?)\)\s*$", s)
    if m_paren:
        core = m_paren.group(1).strip()
        qual = m_paren.group(2).strip()
        return (core, qual or None, None, None)

    if "," in s:
        left, right = s.rsplit(",", 1)
        left = left.strip()
        right_stripped = right.strip()

        m_abbr = re.match(r"^([A-Za-z]{2})$", right_stripped)
        if m_abbr:
            st = m_abbr.group(1).upper()
            if st in US_STATE_ABBR:
                return (left, None, st, "US")

        right_norm = norm_text(right_stripped)
        if right_norm in US_STATE_NAME_TO_ABBR:
            st = US_STATE_NAME_TO_ABBR[right_norm]
            return (left, None, st, "US")

        # treat as subregion hint (e.g. Sussex, Haute-Saone, etc.)
        return (left, right_stripped or None, None, None)

    return (s, None, None, None)


# ----------------------------- GeoNames loading -----------------------------

@dataclass(frozen=True)
class Candidate:
    geonameid: str
    name: str
    asciiname: str
    country: str
    admin1: str
    admin2: str
    feature_class: str
    feature_code: str
    population: int

def load_admin1(admin1_path: str) -> Dict[str, str]:
    m = {}
    with open(admin1_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 2 and parts[0].strip():
                m[parts[0].strip()] = parts[1].strip()
    return m

def load_admin2(admin2_path: str) -> Dict[str, str]:
    m = {}
    with open(admin2_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) >= 2 and parts[0].strip():
                m[parts[0].strip()] = parts[1].strip()
    return m

def build_candidates_index(
    geonames_path: str,
    target_keys: set,
    include_admin_features: bool = True,
) -> Dict[str, List[Candidate]]:
    allowed_A_codes = {"ADM1", "ADM2", "ADM3", "ADM4", "ADMD", "ADM5"}
    cand_by_key: Dict[str, List[Candidate]] = {k: [] for k in target_keys}

    def maybe_add(key: str, parts: List[str]) -> None:
        fclass = parts[6]
        fcode = parts[7]
        if fclass == "P":
            pass
        elif include_admin_features and fclass == "A" and fcode in allowed_A_codes:
            pass
        else:
            return

        try:
            pop = int(parts[14]) if parts[14] else 0
        except ValueError:
            pop = 0

        cand_by_key[key].append(
            Candidate(
                geonameid=parts[0],
                name=parts[1],
                asciiname=parts[2],
                country=parts[8],
                admin1=parts[10],
                admin2=parts[11],
                feature_class=fclass,
                feature_code=fcode,
                population=pop,
            )
        )

    # pass 1: name/asciiname
    with open(geonames_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 15:
                continue

            k_ascii = norm_text(parts[2])
            if k_ascii in target_keys:
                maybe_add(k_ascii, parts)

            k_name = norm_text(parts[1])
            if k_name in target_keys and k_name != k_ascii:
                maybe_add(k_name, parts)

    unmatched = {k for k, v in cand_by_key.items() if len(v) == 0}
    if not unmatched:
        return cand_by_key

    # pass 2: alternatenames for remaining unmatched keys
    with open(geonames_path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.strip():
                continue
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 15:
                continue
            alts = parts[3]
            if not alts or not unmatched:
                continue

            for alt in alts.split(","):
                k = norm_text(alt)
                if k in unmatched:
                    maybe_add(k, parts)

    return cand_by_key


# ----------------------------- Overrides (unchanged) -----------------------------

OVERRIDES: Dict[str, Dict[str, Union[str, List[str], bool, List[str]]]] = {
    "gerona":      {"country": "IT", "lookup": ["fosso gerona"]},
    "mantua":      {"country": "IT", "lookup": ["mantova", "mantua"], "prefer_class": "A", "prefer_codes": ["ADM2", "ADM1"]},
    "cheshire":    {"country": "GB", "prefer_class": "A"},
    "padua":       {"country": "IT", "lookup": ["padova", "padua"]},
    "beaconsfield":{"country": "GB"},
    "lugo":        {"country": "IT"},
    "san marino":  {"country": "SM"},
    "devonport":   {"country": "GB"},
    "tournay":     {"country": "BE", "lookup": ["tournai", "tournay"]},
    "berne":       {"country": "CH", "lookup": ["bern", "berne"]},
    "antwerp":     {"country": "BE"},
    "valencia":    {"country": "ES"},
    "kew":         {"country": "GB"},
    "gand":        {"country": "BE", "lookup": ["gent", "ghent", "gand"]},
    "salo":        {"country": "IT"},
    "surrey":      {"country": "GB", "prefer_class": "A"},
    "hanwell":     {"country": "GB"},
    "kensington":  {"country": "GB"},
    "hull":        {"country": "GB"},
    "bernal":      {"country": "AR"},
    "moravia":     {"country": "CZ", "prefer_class": "A"},
    "orleans":     {"country": "FR"},
    "aquila":      {"country": "IT", "lookup": ["l'aquila", "laquila", "l aquila", "aquila"]},
    "leith":       {"country": "GB"},
    "pesth":       {"country": "HU", "lookup": ["pest", "pesth"]},
    "leonardo":    {"country": "IT"},
    "geneva":      {"country": "CH"},
    "san remo":    {"country": "IT", "lookup": ["sanremo", "san remo"]},
    "cumberland":  {"country": "GB", "prefer_class": "A"},
    "lancaster":   {"country": "US", "state_hint": "PA"},
    "alva":        {"country": "GB"},
    "hanley":      {"country": "GB"},
    "franklin":    {"blank": True},
}


# ----------------------------- Main enrichment -----------------------------

def enrich_city_maker(
    df: pd.DataFrame,
    city_col: str = "city_maker",
    geonames_path: str = "allCountries.txt",
    admin1_path: str = "admin1CodesASCII.txt",
    admin2_path: str = "admin2Codes.txt",
    print_ambiguous: bool = True,
    top_k_print: int = 5,
    use_subregion_hint: bool = True,
    hint_bonus: float = 4.0,
) -> pd.DataFrame:
    """
    Adds:
      - country_iso1
      - admin1_name
      - admin2_name
      - candidate_count
      - is_ambiguous

    Uses subregion hint from parentheses or non-US comma suffix to filter/boost candidates.
    """
    out = df.copy()
    if city_col not in out.columns:
        raise ValueError(f"Column '{city_col}' not found.")

    # Prepare unique places
    uniques = pd.Series(out[city_col].dropna().unique())
    parsed = []
    for raw in uniques.tolist():
        core, sub_hint, st_hint, c_hint = parse_place(raw)
        core_key = norm_text(core)
        if core_key:
            parsed.append((raw, core, core_key, sub_hint, st_hint, c_hint))

    if not parsed:
        out["country_iso1"] = pd.NA
        out["admin1_name"] = pd.NA
        out["admin2_name"] = pd.NA
        out["candidate_count"] = pd.NA
        out["is_ambiguous"] = False
        return out

    places = pd.DataFrame(parsed, columns=["place_raw", "place_core", "place_key", "subregion_hint", "state_hint", "country_hint"])

    # Build target keys (include override lookup keys)
    target_keys = set(places["place_key"].unique())
    for _, spec in OVERRIDES.items():
        lookup = spec.get("lookup", None)
        if isinstance(lookup, str):
            target_keys.add(norm_text(lookup))
        elif isinstance(lookup, list):
            for name in lookup:
                target_keys.add(norm_text(name))

    admin1_map = load_admin1(admin1_path)
    admin2_map = load_admin2(admin2_path)
    cand_by_key = build_candidates_index(geonames_path, target_keys, include_admin_features=True)

    def admin_names_for(c: Candidate) -> Tuple[str, str]:
        a1 = admin1_map.get(f"{c.country}.{c.admin1}", "") if c.country and c.admin1 else ""
        a2 = admin2_map.get(f"{c.country}.{c.admin1}.{c.admin2}", "") if c.country and c.admin1 and c.admin2 else ""
        return a1, a2

    def hint_matches(c: Candidate, hint_norm: str) -> bool:
        if not hint_norm:
            return False
        a1, a2 = admin_names_for(c)
        return (hint_norm in norm_text(a1)) or (hint_norm in norm_text(a2))

    def score_candidate(c: Candidate, prefer_class: Optional[str], prefer_codes: Optional[List[str]], hint_norm: str) -> float:
        s = math.log1p(max(c.population, 0))
        if c.feature_class == "P":
            s += 2.0
        if prefer_class and c.feature_class == prefer_class:
            s += 3.0
        if prefer_codes and c.feature_code in set(prefer_codes):
            s += 2.0
        if use_subregion_hint and hint_norm and hint_matches(c, hint_norm):
            s += hint_bonus
        return s

    resolved_rows = []
    ambiguous_reports = []

    for _, r in places.iterrows():
        raw = r["place_raw"]
        core_key = r["place_key"]
        hint_norm = norm_text(r["subregion_hint"]) if (use_subregion_hint and r["subregion_hint"]) else ""

        spec = OVERRIDES.get(core_key, {})
        if spec.get("blank", False):
            resolved_rows.append({
                "place_raw": raw,
                "country_iso1": pd.NA,
                "admin1_name": pd.NA,
                "admin2_name": pd.NA,
                "candidate_count": 0,
                "is_ambiguous": False,
            })
            continue

        forced_country = spec.get("country", None) or r["country_hint"]
        forced_state   = spec.get("state_hint", None) or r["state_hint"]
        prefer_class   = spec.get("prefer_class", None)
        prefer_codes   = spec.get("prefer_codes", None)

        lookup_names = spec.get("lookup", None)
        if isinstance(lookup_names, str):
            lookup_keys = [norm_text(lookup_names)]
        elif isinstance(lookup_names, list):
            lookup_keys = [norm_text(x) for x in lookup_names]
        else:
            lookup_keys = [core_key]

        # gather candidates (dedupe)
        candidates = []
        seen = set()
        for lk in lookup_keys:
            for c in cand_by_key.get(lk, []):
                if c.geonameid not in seen:
                    seen.add(c.geonameid)
                    candidates.append(c)

        # forced country filter (hard)
        if forced_country:
            candidates = [c for c in candidates if c.country == forced_country]

        # forced US state filter when possible (hard)
        if forced_state:
            candidates2 = [c for c in candidates if c.country == "US" and c.admin1 == forced_state]
            if candidates2:
                candidates = candidates2

        # if forced country yields nothing: blank (your rule)
        if forced_country and not candidates:
            resolved_rows.append({
                "place_raw": raw,
                "country_iso1": pd.NA,
                "admin1_name": pd.NA,
                "admin2_name": pd.NA,
                "candidate_count": 0,
                "is_ambiguous": False,
            })
            continue

        # NEW: subregion hint narrowing
        if use_subregion_hint and hint_norm and len(candidates) > 1:
            matching = [c for c in candidates if hint_matches(c, hint_norm)]
            if matching:
                candidates = matching  # only narrow if it actually helps

        cand_count = len(candidates)
        is_amb = cand_count > 1

        if candidates:
            scored = [(score_candidate(c, prefer_class, prefer_codes, hint_norm), c) for c in candidates]
            scored.sort(key=lambda t: t[0], reverse=True)
            best = scored[0][1]

            country_iso1 = best.country or pd.NA
            a1_key = f"{best.country}.{best.admin1}" if best.country and best.admin1 else None
            admin1_name = admin1_map.get(a1_key, pd.NA) if a1_key else pd.NA
            a2_key = f"{best.country}.{best.admin1}.{best.admin2}" if best.country and best.admin1 and best.admin2 else None
            admin2_name = admin2_map.get(a2_key, pd.NA) if a2_key else pd.NA

            # Print remaining ambiguous cases (excluding overrides)
            if print_ambiguous and is_amb and core_key not in OVERRIDES:
                top = scored[:top_k_print]
                opts = []
                for s_val, c in top:
                    a1, a2 = admin_names_for(c)
                    opts.append((s_val, c.name, c.asciiname, c.country, a1, a2, c.feature_class, c.feature_code, c.population))
                ambiguous_reports.append((raw, cand_count, r["subregion_hint"], opts))
        else:
            country_iso1 = pd.NA
            admin1_name = pd.NA
            admin2_name = pd.NA

        resolved_rows.append({
            "place_raw": raw,
            "country_iso1": country_iso1,
            "admin1_name": admin1_name,
            "admin2_name": admin2_name,
            "candidate_count": cand_count,
            "is_ambiguous": bool(is_amb),
        })

    mapping = pd.DataFrame(resolved_rows).drop_duplicates("place_raw")
    out = out.merge(mapping, left_on=city_col, right_on="place_raw", how="left").drop(columns=["place_raw"])
    out["is_ambiguous"] = out["is_ambiguous"].fillna(False).astype(bool)

    if print_ambiguous and ambiguous_reports:
        print("\n--- Ambiguous place names (not covered by overrides) ---")
        for raw, n, hint, opts in ambiguous_reports:
            hint_txt = f" | hint='{hint}'" if hint else ""
            print(f"\nAMBIGUOUS: '{raw}' (candidates={n}{hint_txt})")
            for s_val, name, asciiname, cc, a1, a2, fcl, fcd, pop in opts:
                a1_txt = f" | admin1={a1}" if a1 else ""
                a2_txt = f" | admin2={a2}" if a2 else ""
                print(f"  score={s_val:0.3f} | {name} ({asciiname}) | {cc}{a1_txt}{a2_txt} | {fcl}/{fcd} | pop={pop}")

    return out

In [21]:

df2 = enrich_city_maker(df, city_col="city_maker",
                        geonames_path="Data/Geo_Data/allCountries.txt",
                        admin1_path="Data/Geo_Data/admin1CodesASCII.txt",
                        admin2_path="Data/Geo_Data/admin2Codes.txt",
                        print_ambiguous=True)

--- Ambiguous place names (not covered by overrides) ---

AMBIGUOUS: 'Wallgau' (candidates=2)
  score=9.277 | Wallgau (Wallgau) | DE | admin1=Bavaria | admin2=Upper Bavaria | P/PPLA4 | pop=1446
  score=7.324 | Wallgau (Wallgau) | DE | admin1=Bavaria | admin2=Upper Bavaria | A/ADM4 | pop=1516

AMBIGUOUS: 'Paris' (candidates=59)
  score=16.576 | Paris (Paris) | FR | admin1=Île-de-France | admin2=Paris | P/PPLC | pop=2138551
  score=15.293 | Paris (Paris) | FR | admin1=Île-de-France | admin2=Paris | A/ADM3 | pop=4380654
  score=14.600 | Paris (Paris) | FR | admin1=Île-de-France | admin2=Paris | A/ADM4 | pop=2190327
  score=14.533 | Paris (Paris) | FR | admin1=Île-de-France | admin2=Paris | A/ADM2 | pop=2048472
  score=12.118 | Paris (Paris) | US | admin1=Texas | admin2=Lamar County | P/PPLA2 | pop=24782

AMBIGUOUS: 'Mirecourt' (candidates=2)
  score=10.854 | Mirecourt (Mirecourt) | FR | admin1=Grand Est | admin2=Vosges | P/PPL | pop=6998
  score=8.573 | Mirecourt (Mirecourt) | FR | admin1=Grand Est | admin2=Vosges | A/ADM4 | pop=5285

AMBIGUOUS: 'London' (candidates=34)
  score=18.009 | London (London) | GB | admin1=England | admin2=Greater London | P/PPLC | pop=8961989
  score=14.954 | London (London) | CA | admin1=Ontario | admin2=Middlesex County | P/PPL | pop=422324
  score=11.216 | London (London) | US | admin1=Ohio | admin2=Madison County | P/PPLA2 | pop=10060
  score=11.003 | London (London) | US | admin1=Kentucky | admin2=Laurel County | P/PPLA2 | pop=8126
  score=9.534 | London (London) | US | admin1=California | admin2=Tulare County | P/PPL | pop=1869

AMBIGUOUS: 'Copenhagen' (candidates=6)
  score=15.958 | Copenhagen (Copenhagen) | DK | admin1=Capital Region | admin2=København | P/PPLC | pop=1153615
  score=8.686 | Copenhagen (Copenhagen) | US | admin1=New York | admin2=Lewis County | P/PPL | pop=800
  score=2.000 | Copenhagen (Copenhagen) | CA | admin1=Ontario | admin2=Elgin County | P/PPL | pop=0
  score=2.000 | Copenhagen (Copenhagen) | GB | admin1=Wales | admin2=Denbighshire | P/PPLX | pop=0
  score=2.000 | Copenhagen (Copenhagen) | US | admin1=Louisiana | admin2=Caldwell Parish | P/PPL | pop=0

AMBIGUOUS: 'Manchester' (candidates=44)
  score=15.252 | Manchester (Manchester) | GB | admin1=England | admin2=Manchester | P/PPLA2 | pop=568996
  score=13.610 | Manchester (Manchester) | US | admin1=New Hampshire | admin2=Hillsborough County | P/PPL | pop=110229
  score=13.202 | Manchester (Manchester) | GB | admin1=England | admin2=Manchester | A/ADM2 | pop=541263
  score=12.328 | Manchester (Manchester) | US | admin1=Connecticut | admin2=Capitol Planning Region | P/PPL | pop=30577
  score=12.164 | Manchester (Manchester) | JM | admin1=Manchester | A/ADM1 | pop=191796

AMBIGUOUS: 'Markneukirchen' (candidates=2)
  score=10.867 | Markneukirchen (Markneukirchen) | DE | admin1=Saxony | P/PPL | pop=7095
  score=8.862 | Markneukirchen (Markneukirchen) | DE | admin1=Saxony | A/ADM4 | pop=7061

AMBIGUOUS: 'Brussels' (candidates=4)
  score=15.834 | Brussels (Brussels) | BE | admin1=Brussels Capital | admin2=Bruxelles-Capitale | P/PPLC | pop=1019022
  score=9.055 | Brussels (Brussels) | CA | admin1=Ontario | admin2=Huron County | P/PPL | pop=1158
  score=9.013 | Brussels (Brussels) | US | admin1=Wisconsin | admin2=Door County | P/PPL | pop=1110
  score=6.920 | Brussels (Brussels) | US | admin1=Illinois | admin2=Calhoun County | P/PPL | pop=136

AMBIGUOUS: 'Milan' (candidates=46)
  score=16.131 | Milan (Milan) | IT | admin1=Lombardy | admin2=Città metropolitana di Milano | P/PPLA | pop=1371498
  score=10.964 | Milan (Milan) | US | admin1=Tennessee | admin2=Gibson County | P/PPL | pop=7813
  score=10.924 | Milán (Milan) | CO | admin1=Caquetá | admin2=Milán | P/PPLA2 | pop=7507
  score=10.697 | Milan (Milan) | US | admin1=Michigan | admin2=Monroe County | P/PPL | pop=5983
  score=10.536 | Milan (Milan) | US | admin1=Illinois | admin2=Rock Island County | P/PPL | pop=5096

AMBIGUOUS: 'Turin' (candidates=16)
  score=15.650 | Turin (Turin) | IT | admin1=Piedmont | admin2=Torino | P/PPLA | pop=847287
  score=11.378 | Turín (Turin) | SV | admin1=Ahuachapán | P/PPL | pop=11829
  score=7.841 | Turin (Turin) | US | admin1=Georgia | admin2=Coweta County | P/PPL | pop=343
  score=7.442 | Turin (Turin) | US | admin1=New York | admin2=Lewis County | P/PPL | pop=230
  score=6.205 | Turin (Turin) | US | admin1=Iowa | admin2=Monona County | P/PPL | pop=66

AMBIGUOUS: 'Vidigulfo' (candidates=2)
  score=10.463 | Vidigulfo (Vidigulfo) | IT | admin1=Lombardy | admin2=Provincia di Pavia | P/PPLA3 | pop=4735
  score=8.781 | Vidigulfo (Vidigulfo) | IT | admin1=Lombardy | admin2=Provincia di Pavia | A/ADM3 | pop=6508

AMBIGUOUS: 'Pavia' (candidates=10)
  score=13.093 | Pavia (Pavia) | IT | admin1=Lombardy | admin2=Provincia di Pavia | P/PPLA2 | pop=65734
  score=11.220 | Pavia (Pavia) | PH | admin1=Western Visayas | admin2=Province of Iloilo | A/ADM3 | pop=74594
  score=11.199 | Pavia (Pavia) | IT | admin1=Lombardy | admin2=Provincia di Pavia | A/ADM3 | pop=73086
  score=10.688 | Pavia (Pavia) | PH | admin1=Western Visayas | admin2=Province of Iloilo | P/PPLA3 | pop=5928
  score=6.574 | Pavia (Pavia) | PT | admin1=Évora | admin2=Mora | A/ADM3 | pop=715

AMBIGUOUS: 'Bologna' (candidates=6)
  score=14.886 | Bologna (Bologna) | IT | admin1=Emilia-Romagna | admin2=Bologna | P/PPLA | pop=394843
  score=13.830 | Bologna (Bologna) | IT | admin1=Emilia-Romagna | admin2=Bologna | A/ADM2 | pop=1014619
  score=12.876 | Bologna (Bologna) | IT | admin1=Emilia-Romagna | admin2=Bologna | A/ADM3 | pop=390636
  score=5.332 | Bologna (Bologna) | IT | admin1=Piedmont | admin2=Provincia di Asti | P/PPL | pop=27
  score=4.944 | Bologna (Bologna) | IT | admin1=Emilia-Romagna | admin2=Provincia di Ferrara | P/PPL | pop=18

AMBIGUOUS: 'Bolzano' (candidates=3)
  score=13.585 | Bolzano (Bolzano) | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | P/PPLA2 | pop=107436
  score=13.183 | Bolzano (Bolzano) | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | A/ADM2 | pop=531178
  score=2.000 | Bolzano (Bolzano) | IT | admin1=Friuli Venezia Giulia | admin2=Udine | P/PPL | pop=0

AMBIGUOUS: 'Graz' (candidates=2)
  score=14.622 | Graz (Graz) | AT | admin1=Styria | admin2=Graz Stadt | P/PPLA | pop=303270
  score=12.556 | Graz (Graz) | AT | admin1=Styria | admin2=Graz Stadt | A/ADM3 | pop=283869

AMBIGUOUS: 'Gorham' (candidates=6)
  score=10.837 | Gorham (Gorham) | US | admin1=Maine | admin2=Cumberland County | P/PPL | pop=6882
  score=9.378 | Gorham (Gorham) | US | admin1=New Hampshire | admin2=Coos County | P/PPL | pop=1600
  score=8.426 | Gorham (Gorham) | US | admin1=New York | admin2=Ontario County | P/PPL | pop=617
  score=7.832 | Gorham (Gorham) | US | admin1=Kansas | admin2=Russell County | P/PPL | pop=340
  score=7.455 | Gorham (Gorham) | US | admin1=Illinois | admin2=Jackson County | P/PPL | pop=233

AMBIGUOUS: 'Nantes' (candidates=10)
  score=14.692 | Nantes (Nantes) | FR | admin1=Pays de la Loire | admin2=Loire-Atlantique | P/PPLA | pop=325070
  score=12.634 | Nantes (Nantes) | FR | admin1=Pays de la Loire | admin2=Loire-Atlantique | A/ADM4 | pop=306694
  score=9.886 | Nantes (Nantes) | BR | admin1=São Paulo | admin2=Nantes | P/PPL | pop=2660
  score=8.065 | Nantes (Nantes) | BR | admin1=São Paulo | admin2=Nantes | A/ADM2 | pop=3179
  score=2.000 | Nantes (Nantes) | CA | admin1=Quebec | admin2=Estrie | P/PPL | pop=0

AMBIGUOUS: 'Birmingham' (candidates=20)
  score=15.962 | Birmingham (Birmingham) | GB | admin1=England | admin2=City and Borough of Birmingham | P/PPLA2 | pop=1157603
  score=14.188 | Birmingham (Birmingham) | US | admin1=Alabama | admin2=Jefferson County | P/PPLA2 | pop=196357
  score=11.945 | Birmingham (Birmingham) | US | admin1=Michigan | admin2=Oakland County | P/PPL | pop=20857
  score=8.073 | Birmingham (Birmingham) | US | admin1=Iowa | admin2=Van Buren County | P/PPL | pop=433
  score=7.268 | Birmingham (Birmingham) | US | admin1=Missouri | admin2=Clay County | P/PPL | pop=193

AMBIGUOUS: 'Munich' (candidates=4)
  score=16.047 | Munich (Munich) | DE | admin1=Bavaria | admin2=Upper Bavaria | P/PPLA | pop=1260391
  score=7.313 | Munich (Munich) | US | admin1=North Dakota | admin2=Cavalier County | P/PPL | pop=202
  score=2.000 | Munich (Munich) | GD | admin1=Saint Andrew Parish | P/PPL | pop=0
  score=2.000 | Munich (Munich) | PE | admin1=Loreto | admin2=Provincia de Maynas | P/PPLX | pop=0

AMBIGUOUS: 'Barnstaple' (candidates=4)
  score=12.361 | Barnstaple (Barnstaple) | GB | admin1=England | admin2=Devon | P/PPL | pop=31616
  score=2.000 | Barnstaple (Barnstaple) | JM | admin1=Trelawny Parish | admin2=Jackson Town | P/PPL | pop=0
  score=2.000 | Barnstaple (Barnstaple) | JM | admin1=Saint Ann Parish | admin2=Madras | P/PPL | pop=0
  score=0.000 | Barnstaple (Barnstaple) | GB | admin1=England | admin2=Devon | A/ADM4 | pop=0

AMBIGUOUS: 'Madrid' (candidates=29)
  score=16.996 | Madrid (Madrid) | ES | admin1=Madrid | admin2=Provincia de Madrid | P/PPLC | pop=3255944
  score=14.989 | Madrid (Madrid) | ES | admin1=Madrid | admin2=Provincia de Madrid | A/ADM3 | pop=3233527
  score=13.813 | Madrid (Madrid) | CO | admin1=Cundinamarca | admin2=Madrid | P/PPLA2 | pop=135000
  score=11.351 | Madrid (Madrid) | CO | admin1=Cundinamarca | admin2=Madrid | A/ADM2 | pop=85090
  score=10.240 | Madrid (Madrid) | MX | admin1=Colima | admin2=Tecomán | P/PPL | pop=3790

AMBIGUOUS: 'Naples' (candidates=14)
  score=15.720 | Naples (Naples) | IT | admin1=Campania | admin2=Napoli | P/PPLA | pop=909048
  score=11.976 | Naples (Naples) | US | admin1=Florida | admin2=Collier County | P/PPLA2 | pop=21512
  score=9.702 | Naples (Naples) | US | admin1=Utah | admin2=Uintah County | P/PPL | pop=2212
  score=9.200 | Naples (Naples) | US | admin1=Texas | admin2=Morris County | P/PPL | pop=1339
  score=8.928 | Naples (Naples) | US | admin1=New York | admin2=Ontario County | P/PPL | pop=1019

AMBIGUOUS: 'Augsburg' (candidates=7)
  score=14.465 | Augsburg (Augsburg) | DE | admin1=Bavaria | admin2=Swabia | P/PPLA2 | pop=259196
  score=12.615 | Augsburg (Augsburg) | DE | admin1=Bavaria | admin2=Swabia | A/ADM4 | pop=301105
  score=2.000 | Augsburg (Augsburg) | CA | admin1=Ontario | admin2=Renfrew County | P/PPL | pop=0
  score=2.000 | Augsburg (Augsburg) | DE | admin1=Schleswig-Holstein | P/PPL | pop=0
  score=2.000 | Augsburg (Augsburg) | US | admin1=Arkansas | admin2=Pope County | P/PPL | pop=0

AMBIGUOUS: 'Cremona' (candidates=5)
  score=13.174 | Cremona (Cremona) | IT | admin1=Lombardy | admin2=Provincia di Cremona | P/PPLA2 | pop=71223
  score=11.194 | Cremona (Cremona) | IT | admin1=Lombardy | admin2=Provincia di Cremona | A/ADM3 | pop=72680
  score=8.082 | Cremona (Cremona) | CA | admin1=Alberta | admin2=Mountain View County | P/PPL | pop=437
  score=2.000 | Cremona (Cremona) | US | admin1=Maryland | admin2=Saint Mary's County | P/PPL | pop=0
  score=0.000 | Cremona (Cremona) | CA | admin1=Alberta | admin2=Cremona | A/ADM2 | pop=0

AMBIGUOUS: 'Edinburgh' (candidates=10)
  score=15.152 | Edinburgh (Edinburgh) | GB | admin1=Scotland | admin2=City of Edinburgh | P/PPLA | pop=514990
  score=10.422 | Edinburgh (Edinburgh) | US | admin1=Indiana | admin2=Johnson County | P/PPL | pop=4546
  score=7.707 | Edinburgh (Edinburgh) | AU | admin1=South Australia | admin2=Salisbury | P/PPLX | pop=300
  score=2.000 | Edinburgh (Edinburgh) | GY | admin1=Essequibo Islands-West Demerara | P/PPL | pop=0
  score=2.000 | Edinburgh (Edinburgh) | JM | admin1=Manchester | admin2=Snowdon | P/PPLX | pop=0

AMBIGUOUS: 'Lugano' (candidates=4)
  score=13.054 | Lugano (Lugano) | CH | admin1=Ticino | admin2=Lugano District | P/PPLA2 | pop=63185
  score=11.045 | Lugano (Lugano) | CH | admin1=Ticino | admin2=Lugano District | A/ADM3 | pop=62615
  score=2.000 | Lugano (Lugano) | BR | admin1=Rio de Janeiro | admin2=Itatiaia | P/PPL | pop=0
  score=2.000 | Lugano (Lugano) | UG | admin1=Eastern Region | admin2=Bugiri District | P/PPL | pop=0

AMBIGUOUS: 'Bangor' (candidates=24)
  score=13.019 | Bangor (Bangor) | GB | admin1=Northern Ireland | admin2=Ards and North Down | P/PPLA2 | pop=61011
  score=12.386 | Bangor (Bangor) | US | admin1=Maine | admin2=Penobscot County | P/PPLA2 | pop=32391
  score=11.816 | Bangor (Bangor) | GB | admin1=Wales | admin2=Gwynedd | P/PPL | pop=18322
  score=10.607 | Bangor (Bangor) | AU | admin1=New South Wales | admin2=Sutherland | P/PPLX | pop=5471
  score=10.557 | Bangor (Bangor) | US | admin1=Pennsylvania | admin2=Northampton County | P/PPL | pop=5203

AMBIGUOUS: 'Vienna' (candidates=19)
  score=16.341 | Vienna (Vienna) | AT | admin1=Vienna | admin2=Wien Stadt | P/PPLC | pop=1691468
  score=11.713 | Vienna (Vienna) | US | admin1=Virginia | admin2=Fairfax County | P/PPL | pop=16522
  score=11.266 | Vienna (Vienna) | US | admin1=West Virginia | admin2=Wood County | P/PPL | pop=10573
  score=10.237 | Vienna (Vienna) | US | admin1=Georgia | admin2=Dooly County | P/PPLA2 | pop=3777
  score=9.407 | Vienna (Vienna) | US | admin1=Illinois | admin2=Johnson County | P/PPLA2 | pop=1647

AMBIGUOUS: 'Grand Rapids, MI' (candidates=2)
  score=14.181 | Grand Rapids (Grand Rapids) | US | admin1=Michigan | admin2=Kent County | P/PPLA2 | pop=195097
  score=2.000 | Grand Rapids (Grand Rapids) | US | admin1=Michigan | admin2=Ontonagon County | P/PPL | pop=0

AMBIGUOUS: 'Salerno' (candidates=4)
  score=13.742 | Salerno (Salerno) | IT | admin1=Campania | admin2=Provincia di Salerno | P/PPLA2 | pop=125797
  score=11.801 | Salerno (Salerno) | IT | admin1=Campania | admin2=Provincia di Salerno | A/ADM3 | pop=133364
  score=5.970 | Salerno (Salerno) | IT | admin1=Lombardy | admin2=Provincia di Pavia | P/PPL | pop=52
  score=2.000 | Salerno (Salerno) | PK | admin1=Punjab | admin2=Okāra District | P/PPL | pop=0

AMBIGUOUS: 'Colle' (candidates=41)
  score=8.114 | Colle (Colle) | IT | admin1=Umbria | admin2=Provincia di Terni | P/PPL | pop=451
  score=7.869 | Colle (Colle) | IT | admin1=Veneto | admin2=Provincia di Vicenza | P/PPL | pop=353
  score=7.412 | Colle (Colle) | IT | admin1=Friuli Venezia Giulia | admin2=Pordenone | P/PPL | pop=223
  score=7.165 | Colle (Colle) | IT | admin1=Trentino-Alto Adige | admin2=Bolzano | P/PPL | pop=174
  score=7.004 | Colle (Colle) | IT | admin1=The Marches | admin2=Provincia di Ascoli Piceno | P/PPL | pop=148

AMBIGUOUS: 'Florence' (candidates=47)
  score=14.814 | Florence (Florence) | IT | admin1=Tuscany | admin2=Province of Florence | P/PPLA | pop=367150
  score=12.597 | Florence (Florence) | US | admin1=Alabama | admin2=Lauderdale County | P/PPLA2 | pop=40026
  score=12.551 | Florence (Florence) | US | admin1=South Carolina | admin2=Florence County | P/PPLA2 | pop=38228
  score=12.381 | Florence (Florence) | US | admin1=Kentucky | admin2=Boone County | P/PPL | pop=32227
  score=12.345 | Florence (Florence) | US | admin1=Arizona | admin2=Pinal County | P/PPLA2 | pop=31110

AMBIGUOUS: 'Como' (candidates=27)
  score=13.348 | Como (Como) | IT | admin1=Lombardy | admin2=Provincia di Como | P/PPLA2 | pop=84808
  score=11.602 | Como (Como) | AU | admin1=Western Australia | admin2=South Perth | P/PPLX | pop=14786
  score=11.321 | Como (Como) | IT | admin1=Lombardy | admin2=Provincia di Como | A/ADM3 | pop=82522
  score=10.266 | Como (Como) | AU | admin1=New South Wales | admin2=Sutherland | P/PPLX | pop=3890
  score=9.875 | Como (Como) | US | admin1=Wisconsin | admin2=Walworth County | P/PPL | pop=2631

AMBIGUOUS: 'Lichfield' (candidates=4)
  score=12.401 | Lichfield (Lichfield) | GB | admin1=England | admin2=Staffordshire | P/PPL | pop=32877
  score=2.000 | Lichfield (Lichfield) | GY | admin1=Mahaica-Berbice | P/PPL | pop=0
  score=2.000 | Lichfield (Lichfield) | NZ | admin1=Waikato Region | admin2=South Waikato District | P/PPL | pop=0
  score=0.000 | Lichfield (Lichfield) | GB | admin1=England | admin2=Staffordshire | A/ADM4 | pop=0

AMBIGUOUS: 'Tottenham' (candidates=4)
  score=13.775 | Tottenham (Tottenham) | GB | admin1=England | admin2=Greater London | P/PPL | pop=130000
  score=10.546 | Tottenham (Tottenham) | CA | admin1=Ontario | admin2=Simcoe County | P/PPL | pop=5143
  score=8.089 | Tottenham (Tottenham) | AU | admin1=New South Wales | admin2=Lachlan | P/PPL | pop=440
  score=2.000 | Tottenham (Tottenham) | AU | admin1=Victoria | admin2=Maribyrnong | P/PPL | pop=0

AMBIGUOUS: 'Troyes' (candidates=3)
  score=13.015 | Troyes (Troyes) | FR | admin1=Grand Est | admin2=Aube | P/PPLA2 | pop=60785
  score=11.013 | Troyes (Troyes) | FR | admin1=Grand Est | admin2=Aube | A/ADM4 | pop=60640
  score=2.000 | Troyes (Troyes) | FR | admin1=Nouvelle-Aquitaine | admin2=Landes | P/PPL | pop=0

AMBIGUOUS: 'Le Havre' (candidates=3)
  score=14.133 | Le Havre (Le Havre) | FR | admin1=Normandy | admin2=Seine-Maritime | P/PPLA3 | pop=185972
  score=12.046 | Le Havre (Le Havre) | FR | admin1=Normandy | admin2=Seine-Maritime | A/ADM4 | pop=170352
  score=2.000 | Le Havre (Le Havre) | FR | admin1=Normandy | admin2=Manche | P/PPL | pop=0

AMBIGUOUS: 'Rome' (candidates=33)
  score=16.657 | Rome (Rome) | IT | admin1=Lazio | admin2=Città metropolitana di Roma Capitale | P/PPLC | pop=2318895
  score=12.500 | Rome (Rome) | US | admin1=Georgia | admin2=Floyd County | P/PPLA2 | pop=36323
  score=12.391 | Rome (Rome) | US | admin1=New York | admin2=Oneida County | P/PPL | pop=32573
  score=9.900 | Rome (Rome) | US | admin1=Wisconsin | admin2=Adams County | P/PPL | pop=2697
  score=9.461 | Rome (Rome) | US | admin1=Illinois | admin2=Peoria County | P/PPL | pop=1738

AMBIGUOUS: 'Palermo' (candidates=70)
  score=15.382 | Palermo (Palermo) | IT | admin1=Sicily | admin2=Palermo | P/PPLA | pop=648260
  score=14.041 | Palermo (Palermo) | IT | admin1=Sicily | admin2=Palermo | A/ADM2 | pop=1252588
  score=13.405 | Palermo (Palermo) | IT | admin1=Sicily | admin2=Palermo | A/ADM3 | pop=663401
  score=11.200 | Palermo (Palermo) | CO | admin1=Huila Department | admin2=Palermo | P/PPLA2 | pop=9896
  score=10.591 | Palermo (Palermo) | US | admin1=California | admin2=Butte County | P/PPL | pop=5382

AMBIGUOUS: 'Caltanisetta' (candidates=2)
  score=13.048 | Caltanissetta (Caltanissetta) | IT | admin1=Sicily | admin2=Provincia di Caltanissetta | P/PPLA2 | pop=62797
  score=12.478 | Provincia di Caltanissetta (Provincia di Caltanissetta) | IT | admin1=Sicily | admin2=Provincia di Caltanissetta | A/ADM2 | pop=262458

AMBIGUOUS: 'Berlin' (candidates=146)
  score=17.047 | Berlin (Berlin) | DE | admin1=State of Berlin | P/PPLC | pop=3426354
  score=15.120 | Berlin (Berlin) | DE | admin1=State of Berlin | A/ADM4 | pop=3685265
  score=11.334 | Berlín (Berlin) | SV | admin1=Usulután | P/PPL | pop=11313
  score=11.145 | Berlin (Berlin) | US | admin1=New Hampshire | admin2=Coos County | P/PPL | pop=9367
  score=10.935 | Berlin (Berlin) | US | admin1=New Jersey | admin2=Camden County | P/PPL | pop=7590

AMBIGUOUS: 'Pisa' (candidates=17)
  score=13.608 | Pisa (Pisa) | IT | admin1=Tuscany | admin2=Province of Pisa | P/PPLA2 | pop=109960
  score=11.395 | Pisa (Pisa) | IT | admin1=Tuscany | admin2=Province of Pisa | A/ADM3 | pop=88880
  score=3.386 | Pisa (Pisa) | PE | admin1=Arequipa | admin2=Provincia de Caylloma | P/PPL | pop=3
  score=2.000 | Pisa (Pisa) | CN | admin1=Yunnan | admin2=Wenshan Zhuangzu Miaozu Zizhizhou | P/PPL | pop=0
  score=2.000 | Pisa (Pisa) | CO | admin1=Sucre Department | admin2=Majagual | P/PPL | pop=0

AMBIGUOUS: 'Leeds' (candidates=21)
  score=15.192 | Leeds (Leeds) | GB | admin1=England | admin2=City and Borough of Leeds | P/PPLA2 | pop=536280
  score=11.387 | Leeds (Leeds) | US | admin1=Alabama | admin2=Jefferson County | P/PPL | pop=11936
  score=9.641 | Leeds (Leeds) | US | admin1=Maine | admin2=Androscoggin County | P/PPL | pop=2080
  score=8.737 | Leeds (Leeds) | US | admin1=Utah | admin2=Washington County | P/PPL | pop=842
  score=8.195 | Leeds (Leeds) | JM | admin1=St. Elizabeth | admin2=Leeds | A/ADM2 | pop=3621

AMBIGUOUS: 'Brighton' (candidates=60)

C:\Users\tun62890\AppData\Local\Temp\ipykernel_11680\3646223284.py:449: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  out["is_ambiguous"] = out["is_ambiguous"].fillna(False).astype(bool)

In [4]:
df2.head(50)

,maker_id,maker_name,type,city_maker,auction_house,sale_date,lot,usd,gbp,eur,bold_currency,country_iso1,admin1_name,admin2_name,candidate_count,is_ambiguous
0,2919,"Achner, Michael",Violin,Wallgau,Tarisio,"Feb 20, 2010",354,4200.0,2721.0,3107.0,usd,DE,Bavaria,Upper Bavaria,2.0,True
1,2919,"Achner, Michael",Violin,Mittenwald,Bongartz's,"Apr 27, 1987",145,2838.0,1702.0,NaN,NaN,DE,Bavaria,Upper Bavaria,1.0,False
2,2611,"Achner, Philip",Violin,Mittenwald,Tarisio,"May 17, 2018",123,24000.0,17759.0,20330.0,usd,DE,Bavaria,Upper Bavaria,1.0,False
3,2611,"Achner, Philip",Violin,NaN,Bongartz's,"Nov 15, 2008",138,3884.0,2613.0,3064.0,NaN,NaN,NaN,NaN,NaN,False
4,2611,"Achner, Philip",Violin,Mittenwald,Sotheby's,"Mar 27, 1990",16,2146.0,1320.0,NaN,NaN,DE,Bavaria,Upper Bavaria,1.0,False
5,890,"Acoulon, Alexandre Alfred",Violin Bow,NaN,NaN,"May 30, 2025",NaN,2400.0,1780.0,2117.0,NaN,NaN,NaN,NaN,NaN,False
6,890,"Acoulon, Alexandre Alfred",Violin,NaN,Tarisio,"Nov 8, 2019",118,2950.0,2301.0,2675.0,NaN,NaN,NaN,NaN,NaN,False
7,890,"Acoulon, Alexandre Alfred",Violin,Paris,Tarisio,"Oct 16, 2013",202,3000.0,1871.0,2212.0,usd,FR,Île-de-France,Paris,59.0,True
8,890,"Acoulon, Alexandre Alfred",Violin,Mirecourt,Tarisio,"Oct 25, 2007",191,4388.0,2142.0,3067.0,usd,FR,Grand Est,Vosges,2.0,True
9,890,"Acoulon, Alexandre Alfred",Violin Bow,NaN,Bongartz's,"Nov 12, 2005",340,3296.0,1897.0,2818.0,NaN,NaN,NaN,NaN,NaN,False
10,890,"Acoulon, Alexandre Alfred",Cello,NaN,Bonhams,"Sep 6, 2004",142,8082.0,4541.0,6696.0,NaN,NaN,NaN,NaN,NaN,False
11,890,"Acoulon, Alexandre Alfred",Violin,Paris,Bonhams,"Jul 19, 1994",156,1365.0,880.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
12,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Sep 19, 1991",206,2280.0,1320.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
13,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Mar 13, 1991",137,694.0,374.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
14,890,"Acoulon, Alexandre Alfred",Violin,Mirecourt,Phillip's,"Jun 22, 1989",57,874.0,563.0,NaN,NaN,FR,Grand Est,Vosges,2.0,True
15,890,"Acoulon, Alexandre Alfred",Violin,NaN,Phillip's,"Jun 16, 1988",89,2147.0,1202.0,NaN,NaN,NaN,NaN,NaN,NaN,False
16,890,"Acoulon, Alexandre Alfred",Violin,NaN,Phillip's,"Apr 14, 1988",105,2626.0,1400.0,NaN,NaN,NaN,NaN,NaN,NaN,False
17,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Sotheby's,"Jun 9, 1987",236,658.0,396.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
18,890,"Acoulon, Alexandre Alfred",Violin,Paris,Christie's,"Mar 18, 1986",141,1037.0,702.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
19,890,"Acoulon, Alexandre Alfred",Violin,Paris,Phillip's,"Mar 27, 1986",98,1436.0,968.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
20,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Bongartz's,"Nov 18, 1985",218,295.0,207.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
21,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Oct 17, 1985",135,498.0,352.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True
22,1662,"Acton, William John",Violin,London,Bonhams,"Mar 12, 2002",299,488.0,345.0,559.0,gbp,GB,England,Greater London,34.0,True
23,1662,"Acton, William John",Cello,NaN,Sotheby's,"Nov 13, 2001",93,3173.0,2200.0,3589.0,NaN,NaN,NaN,NaN,NaN,False
24,1662,"Acton, William John",Cello,London,Sotheby's,"Nov 13, 2001",95,3808.0,2640.0,4307.0,gbp,GB,England,Greater London,34.0,True
25,1662,"Acton, William John",Cello,NaN,Gardiner-Houlgate,"Nov 12, 2000",192,6909.0,4830.0,7966.0,NaN,NaN,NaN,NaN,NaN,False
26,1662,"Acton, William John",Cello,London,Phillip's,"Jul 23, 1992",170,1157.0,605.0,NaN,NaN,GB,England,Greater London,34.0,True
27,1662,"Acton, William John",Violin,London,Phillip's,"Oct 24, 1991",186,104.0,61.0,NaN,NaN,GB,England,Greater London,34.0,True
28,1662,"Acton, William John",Violin,NaN,Phillip's,"Oct 22, 1987",87,363.0,220.0,NaN,NaN,NaN,NaN,NaN,NaN,False
29,1662,"Acton, William John",Violin,NaN,Sotheby's,"Jun 9, 1987",192,365.0,220.0,NaN,NaN,NaN,NaN,NaN,NaN,False
30,1662,"Acton, William John",Violin,NaN,Phillip's,"Dec 18, 1986",45,441.0,308.0,NaN,NaN,NaN,NaN,NaN,NaN,False
31,1662,"Acton, William John",Violin,NaN,Phillip's,"Jul 19, 1984",99,292.0,220.0,NaN,NaN,NaN,NaN,NaN,NaN,False
32,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,NaN,"Jun 5, 2025",NaN,19276.0,14207.0,16875.0,NaN,NaN,NaN,NaN,NaN,False
33,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,NaN,"Feb 27, 2024",NaN,19513.0,15399.0,18000.0,NaN,NaN,NaN,NaN,NaN,False
34,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,NaN,"Nov 17, 2023",NaN,21600.0,17393.0,19872.0,NaN,NaN,NaN,NaN,NaN,False
35,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Tarisio,"Oct 25, 2022",99,32894.0,28638.0,33000.0,NaN,NaN,NaN,NaN,NaN,False
36,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Vichy-Enchères,"Dec 3, 2020",92,84440.0,62741.0,69440.0,NaN,NaN,NaN,NaN,NaN,False
37,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Vichy-Enchères,"Dec 3, 2020",229,22618.0,16806.0,18600.0,NaN,NaN,NaN,NaN,NaN,False
38,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Vichy-Enchères,"Dec 3, 2020",340,30157.0,22407.0,24800.0,NaN,NaN,NaN,NaN,NaN,False
39,1988,"Adam, Jean 'Grand'",Viola Bow,NaN,Tarisio,"Mar 24, 2020",52,9129.0,7800.0,8465.0,NaN,NaN,NaN,NaN,NaN,False
40,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Ingles & Hayday,"Oct 19, 2019",156,24923.0,19200.0,22313.0,gbp,FR,Grand Est,Vosges,2.0,True
41,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Tarisio,"Mar 18, 2019",26,23833.0,18000.0,21008.0,NaN,NaN,NaN,NaN,NaN,False
42,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Vichy-Enchères,"Dec 5, 2018",172,67394.0,53009.0,59520.0,NaN,NaN,NaN,NaN,NaN,False
43,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Vichy-Enchères,"Dec 5, 2018",222,33697.0,26504.0,29760.0,NaN,NaN,NaN,NaN,NaN,False
44,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Tarisio,"Oct 29, 2018",118,9503.0,7416.0,8347.0,NaN,NaN,NaN,NaN,NaN,False
45,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Tarisio,"May 17, 2018",20,27600.0,20422.0,23380.0,NaN,NaN,NaN,NaN,NaN,False
46,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Tarisio,"Nov 9, 2017",123,18000.0,13736.0,15475.0,NaN,NaN,NaN,NaN,NaN,False
47,1988,"Adam, Jean 'Grand'",Violin Bow,NaN,Vichy-Enchères,"Nov 30, 2017",15,55710.0,41294.0,46800.0,NaN,NaN,NaN,NaN,NaN,False
48,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Tarisio,"Feb 24, 2017",55,13200.0,10549.0,12486.0,NaN,NaN,NaN,NaN,NaN,False
49,1988,"Adam, Jean 'Grand'",Cello Bow,NaN,Tarisio,"Oct 30, 2013",23,24653.0,15340.0,17923.0,NaN,NaN,NaN,NaN,NaN,False

## Filling in Missing Locations

Fill missing location using other rows with the same maker.

method:
- "mode": fill each missing field with the maker-level mode (most frequent non-null) for that field independently (city/country/admin1/admin2).
- "shared_level": (previous behavior) if maker is single-city, fill city+admins from that city. If maker has multiple cities, fill only the highest admin level shared across all non-missing rows (admin2 else admin1 else country).

Adds:
- filled_col: True if any of {city,country,admin1,admin2} was imputed by this function.

In [22]:
def fill_location_from_maker(
    df, method,  # "shared_level" or "mode"
    maker_col="maker_name",
    city_col="city_maker",
    country_col="country_iso1",
    admin1_col="admin1_name",
    admin2_col="admin2_name",
    filled_col="location_filled",
    only_when_city_and_location_missing=True,
    verbose=True,
):

    out = df.copy()

    # Ensure columns exist
    for c in [maker_col, city_col, country_col, admin1_col, admin2_col]:
        if c not in out.columns:
            out[c] = pd.NA

    # Treat empty strings as missing
    for c in [city_col, country_col, admin1_col, admin2_col]:
        out[c] = out[c].replace(r"^\s*$", pd.NA, regex=True)

    before = out[[city_col, country_col, admin1_col, admin2_col]].copy()

    def _mode_nonnull(s):
        s2 = s.dropna()
        return pd.NA if s2.empty else s2.value_counts().idxmax()

    def _shared_or_na(s):
        s2 = s.dropna()
        u = pd.unique(s2)
        return u[0] if len(u) == 1 else pd.NA

    # Eligibility mask
    loc_all_missing = out[[country_col, admin1_col, admin2_col]].isna().all(axis=1)
    city_missing = out[city_col].isna()

    if only_when_city_and_location_missing:
        eligible = city_missing & loc_all_missing & out[maker_col].notna()
    else:
        eligible = (city_missing | loc_all_missing) & out[maker_col].notna()

    method = str(method).strip().casefold()
    if method not in {"shared_level", "mode"}:
        raise ValueError("method must be 'shared_level' or 'mode'")

    if method == "mode":
        # Per maker, compute independent modes for each column
        maker_fill = (
            out[out[maker_col].notna()]
            .groupby(maker_col, sort=False)
            .agg(
                _fill_city=(city_col, _mode_nonnull),
                _fill_country=(country_col, _mode_nonnull),
                _fill_admin1=(admin1_col, _mode_nonnull),
                _fill_admin2=(admin2_col, _mode_nonnull),
            )
            .reset_index()
        )

        out = out.merge(maker_fill, on=maker_col, how="left")

        # Fill NaNs only
        out.loc[eligible, country_col] = out.loc[eligible, country_col].fillna(out.loc[eligible, "_fill_country"])
        out.loc[eligible, admin1_col]  = out.loc[eligible, admin1_col].fillna(out.loc[eligible, "_fill_admin1"])
        out.loc[eligible, admin2_col]  = out.loc[eligible, admin2_col].fillna(out.loc[eligible, "_fill_admin2"])
        out.loc[eligible, city_col]    = out.loc[eligible, city_col].fillna(out.loc[eligible, "_fill_city"])

        out = out.drop(columns=["_fill_city", "_fill_country", "_fill_admin1", "_fill_admin2"], errors="ignore")

    else:
        # shared_level method
        out["_city_key"] = out[city_col].map(lambda x: norm_text(x) if pd.notna(x) else pd.NA)

        def _maker_fill_rule(g):
            city_keys = pd.unique(g["_city_key"].dropna())

            # Single-city maker: fill from that city's rows (mode within that city)
            if len(city_keys) == 1:
                key = city_keys[0]
                gg = g[g["_city_key"] == key]
                return pd.Series(
                    {
                        "_fill_city": _mode_nonnull(gg[city_col]),
                        "_fill_country": _mode_nonnull(gg[country_col]),
                        "_fill_admin1": _mode_nonnull(gg[admin1_col]),
                        "_fill_admin2": _mode_nonnull(gg[admin2_col]),
                        "_single_city": True,
                    }
                )

            # Multi-city maker: fill only highest shared admin level across all rows
            fill_country = _shared_or_na(g[country_col])
            fill_admin1 = _shared_or_na(g[admin1_col]) if pd.notna(fill_country) else pd.NA
            fill_admin2 = _shared_or_na(g[admin2_col]) if pd.notna(fill_admin1) else pd.NA

            return pd.Series(
                {
                    "_fill_city": pd.NA,
                    "_fill_country": fill_country,
                    "_fill_admin1": fill_admin1,
                    "_fill_admin2": fill_admin2,
                    "_single_city": False,
                }
            )

        maker_fill = (
            out[out[maker_col].notna()]
            .groupby(maker_col, sort=False)
            .apply(_maker_fill_rule)
            .reset_index()
        )

        out = out.merge(maker_fill, on=maker_col, how="left")

        out.loc[eligible, country_col] = out.loc[eligible, country_col].fillna(out.loc[eligible, "_fill_country"])
        out.loc[eligible, admin1_col]  = out.loc[eligible, admin1_col].fillna(out.loc[eligible, "_fill_admin1"])
        out.loc[eligible, admin2_col]  = out.loc[eligible, admin2_col].fillna(out.loc[eligible, "_fill_admin2"])

        # Only fill city for single-city makers
        city_fill_mask = eligible & out[city_col].isna() & out["_single_city"].fillna(False)
        out.loc[city_fill_mask, city_col] = out.loc[city_fill_mask, "_fill_city"]

        out = out.drop(columns=["_city_key", "_fill_city", "_fill_country", "_fill_admin1", "_fill_admin2", "_single_city"], errors="ignore")

    # Filled flag
    after = out[[city_col, country_col, admin1_col, admin2_col]]
    sentinel = "__NA__"
    out[filled_col] = (before.fillna(sentinel) != after.fillna(sentinel)).any(axis=1)

    if verbose:
        n = int(out[filled_col].sum())
        m = out.loc[out[filled_col], maker_col].nunique(dropna=True)
        print(f"Filled location for {n} rows across {m} makers (method='{method}').")

    return out

In [23]:
df3 = fill_location_from_maker(df2,method='mode')

Filled location for 16389 rows across 1440 makers (method='mode').

In [15]:
df3.head(50)

,maker_id,maker_name,type,city_maker,auction_house,sale_date,lot,usd,gbp,eur,bold_currency,country_iso1,admin1_name,admin2_name,candidate_count,is_ambiguous,location_filled
0,2919,"Achner, Michael",Violin,Wallgau,Tarisio,"Feb 20, 2010",354,4200.0,2721.0,3107.0,usd,DE,Bavaria,Upper Bavaria,2.0,True,False
1,2919,"Achner, Michael",Violin,Mittenwald,Bongartz's,"Apr 27, 1987",145,2838.0,1702.0,NaN,NaN,DE,Bavaria,Upper Bavaria,1.0,False,False
2,2611,"Achner, Philip",Violin,Mittenwald,Tarisio,"May 17, 2018",123,24000.0,17759.0,20330.0,usd,DE,Bavaria,Upper Bavaria,1.0,False,False
3,2611,"Achner, Philip",Violin,Mittenwald,Bongartz's,"Nov 15, 2008",138,3884.0,2613.0,3064.0,NaN,DE,Bavaria,Upper Bavaria,NaN,False,True
4,2611,"Achner, Philip",Violin,Mittenwald,Sotheby's,"Mar 27, 1990",16,2146.0,1320.0,NaN,NaN,DE,Bavaria,Upper Bavaria,1.0,False,False
5,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,NaN,"May 30, 2025",NaN,2400.0,1780.0,2117.0,NaN,FR,Île-de-France,Paris,NaN,False,True
6,890,"Acoulon, Alexandre Alfred",Violin,Paris,Tarisio,"Nov 8, 2019",118,2950.0,2301.0,2675.0,NaN,FR,Île-de-France,Paris,NaN,False,True
7,890,"Acoulon, Alexandre Alfred",Violin,Paris,Tarisio,"Oct 16, 2013",202,3000.0,1871.0,2212.0,usd,FR,Île-de-France,Paris,59.0,True,False
8,890,"Acoulon, Alexandre Alfred",Violin,Mirecourt,Tarisio,"Oct 25, 2007",191,4388.0,2142.0,3067.0,usd,FR,Grand Est,Vosges,2.0,True,False
9,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Bongartz's,"Nov 12, 2005",340,3296.0,1897.0,2818.0,NaN,FR,Île-de-France,Paris,NaN,False,True
10,890,"Acoulon, Alexandre Alfred",Cello,Paris,Bonhams,"Sep 6, 2004",142,8082.0,4541.0,6696.0,NaN,FR,Île-de-France,Paris,NaN,False,True
11,890,"Acoulon, Alexandre Alfred",Violin,Paris,Bonhams,"Jul 19, 1994",156,1365.0,880.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
12,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Sep 19, 1991",206,2280.0,1320.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
13,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Mar 13, 1991",137,694.0,374.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
14,890,"Acoulon, Alexandre Alfred",Violin,Mirecourt,Phillip's,"Jun 22, 1989",57,874.0,563.0,NaN,NaN,FR,Grand Est,Vosges,2.0,True,False
15,890,"Acoulon, Alexandre Alfred",Violin,Paris,Phillip's,"Jun 16, 1988",89,2147.0,1202.0,NaN,NaN,FR,Île-de-France,Paris,NaN,False,True
16,890,"Acoulon, Alexandre Alfred",Violin,Paris,Phillip's,"Apr 14, 1988",105,2626.0,1400.0,NaN,NaN,FR,Île-de-France,Paris,NaN,False,True
17,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Sotheby's,"Jun 9, 1987",236,658.0,396.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
18,890,"Acoulon, Alexandre Alfred",Violin,Paris,Christie's,"Mar 18, 1986",141,1037.0,702.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
19,890,"Acoulon, Alexandre Alfred",Violin,Paris,Phillip's,"Mar 27, 1986",98,1436.0,968.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
20,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Bongartz's,"Nov 18, 1985",218,295.0,207.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
21,890,"Acoulon, Alexandre Alfred",Violin Bow,Paris,Phillip's,"Oct 17, 1985",135,498.0,352.0,NaN,NaN,FR,Île-de-France,Paris,59.0,True,False
22,1662,"Acton, William John",Violin,London,Bonhams,"Mar 12, 2002",299,488.0,345.0,559.0,gbp,GB,England,Greater London,34.0,True,False
23,1662,"Acton, William John",Cello,London,Sotheby's,"Nov 13, 2001",93,3173.0,2200.0,3589.0,NaN,GB,England,Greater London,NaN,False,True
24,1662,"Acton, William John",Cello,London,Sotheby's,"Nov 13, 2001",95,3808.0,2640.0,4307.0,gbp,GB,England,Greater London,34.0,True,False
25,1662,"Acton, William John",Cello,London,Gardiner-Houlgate,"Nov 12, 2000",192,6909.0,4830.0,7966.0,NaN,GB,England,Greater London,NaN,False,True
26,1662,"Acton, William John",Cello,London,Phillip's,"Jul 23, 1992",170,1157.0,605.0,NaN,NaN,GB,England,Greater London,34.0,True,False
27,1662,"Acton, William John",Violin,London,Phillip's,"Oct 24, 1991",186,104.0,61.0,NaN,NaN,GB,England,Greater London,34.0,True,False
28,1662,"Acton, William John",Violin,London,Phillip's,"Oct 22, 1987",87,363.0,220.0,NaN,NaN,GB,England,Greater London,NaN,False,True
29,1662,"Acton, William John",Violin,London,Sotheby's,"Jun 9, 1987",192,365.0,220.0,NaN,NaN,GB,England,Greater London,NaN,False,True
30,1662,"Acton, William John",Violin,London,Phillip's,"Dec 18, 1986",45,441.0,308.0,NaN,NaN,GB,England,Greater London,NaN,False,True
31,1662,"Acton, William John",Violin,London,Phillip's,"Jul 19, 1984",99,292.0,220.0,NaN,NaN,GB,England,Greater London,NaN,False,True
32,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,NaN,"Jun 5, 2025",NaN,19276.0,14207.0,16875.0,NaN,FR,Grand Est,Vosges,NaN,False,True
33,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,NaN,"Feb 27, 2024",NaN,19513.0,15399.0,18000.0,NaN,FR,Grand Est,Vosges,NaN,False,True
34,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,NaN,"Nov 17, 2023",NaN,21600.0,17393.0,19872.0,NaN,FR,Grand Est,Vosges,NaN,False,True
35,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Tarisio,"Oct 25, 2022",99,32894.0,28638.0,33000.0,NaN,FR,Grand Est,Vosges,NaN,False,True
36,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Vichy-Enchères,"Dec 3, 2020",92,84440.0,62741.0,69440.0,NaN,FR,Grand Est,Vosges,NaN,False,True
37,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Vichy-Enchères,"Dec 3, 2020",229,22618.0,16806.0,18600.0,NaN,FR,Grand Est,Vosges,NaN,False,True
38,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Vichy-Enchères,"Dec 3, 2020",340,30157.0,22407.0,24800.0,NaN,FR,Grand Est,Vosges,NaN,False,True
39,1988,"Adam, Jean 'Grand'",Viola Bow,Mirecourt,Tarisio,"Mar 24, 2020",52,9129.0,7800.0,8465.0,NaN,FR,Grand Est,Vosges,NaN,False,True
40,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Ingles & Hayday,"Oct 19, 2019",156,24923.0,19200.0,22313.0,gbp,FR,Grand Est,Vosges,2.0,True,False
41,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Tarisio,"Mar 18, 2019",26,23833.0,18000.0,21008.0,NaN,FR,Grand Est,Vosges,NaN,False,True
42,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Vichy-Enchères,"Dec 5, 2018",172,67394.0,53009.0,59520.0,NaN,FR,Grand Est,Vosges,NaN,False,True
43,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Vichy-Enchères,"Dec 5, 2018",222,33697.0,26504.0,29760.0,NaN,FR,Grand Est,Vosges,NaN,False,True
44,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Tarisio,"Oct 29, 2018",118,9503.0,7416.0,8347.0,NaN,FR,Grand Est,Vosges,NaN,False,True
45,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Tarisio,"May 17, 2018",20,27600.0,20422.0,23380.0,NaN,FR,Grand Est,Vosges,NaN,False,True
46,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Tarisio,"Nov 9, 2017",123,18000.0,13736.0,15475.0,NaN,FR,Grand Est,Vosges,NaN,False,True
47,1988,"Adam, Jean 'Grand'",Violin Bow,Mirecourt,Vichy-Enchères,"Nov 30, 2017",15,55710.0,41294.0,46800.0,NaN,FR,Grand Est,Vosges,NaN,False,True
48,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Tarisio,"Feb 24, 2017",55,13200.0,10549.0,12486.0,NaN,FR,Grand Est,Vosges,NaN,False,True
49,1988,"Adam, Jean 'Grand'",Cello Bow,Mirecourt,Tarisio,"Oct 30, 2013",23,24653.0,15340.0,17923.0,NaN,FR,Grand Est,Vosges,NaN,False,True

## Fallback Location Filling

Adds:
- level_col: most specific non-missing level in that row: city > admin2 > admin1 > country > none
- best_value_col: the best available value in that row: city if present else admin2 else admin1 else country else NA

Fills missing location fields with the next available coarser level

In [24]:
def fill_location_fallback(
    df,
    city_col="city_maker",
    admin2_col="admin2_name",
    admin1_col="admin1_name",
    country_col="country_iso1",
    level_col="highest_level_known",
    best_value_col="location_best",
):
    out = df.copy()

    # Ensure columns exist
    for c in [city_col, admin2_col, admin1_col, country_col]:
        if c not in out.columns:
            out[c] = pd.NA

    # Treat empty strings as missing
    for c in [city_col, admin2_col, admin1_col, country_col]:
        out[c] = out[c].replace(r"^\s*$", pd.NA, regex=True)

    has_city = out[city_col].notna()
    has_a2   = out[admin2_col].notna()
    has_a1   = out[admin1_col].notna()
    has_ctry = out[country_col].notna()

    # Most specific level known
    out[level_col] = "none"
    out.loc[has_ctry, level_col] = "country"
    out.loc[has_a1,   level_col] = "admin1"
    out.loc[has_a2,   level_col] = "admin2"
    out.loc[has_city, level_col] = "city"

    # Best available value (single column)
    out[best_value_col] = out[city_col]
    out[best_value_col] = out[best_value_col].fillna(out[admin2_col])
    out[best_value_col] = out[best_value_col].fillna(out[admin1_col])
    out[best_value_col] = out[best_value_col].fillna(out[country_col])

    # Fill missing fields with next coarser level (no overwrites)
    out[admin1_col] = out[admin1_col].fillna(out[country_col])
    out[admin2_col] = out[admin2_col].fillna(out[admin1_col])
    out[city_col]   = out[city_col].fillna(out[admin2_col])

    return out

In [25]:
df4 = fill_location_fallback(df3)

In [26]:
df4.to_csv("sales_engineered_grouped_by_region.csv", index=False)

NameError: name 'df2' is not defined